/* Deutsch — Leben im Ausland: von der Ankunft bis zum sozialen Leben. */
(function () {
  'use strict';
  const LOS = window.LOS;
  const abroad = [
    {
      id: 'de-abr-ankunft', cat: 'arrival', title: 'Ankunft: Flughafen, Passkontrolle, Taxi, Hotel', l: 'A2', icon: 'globe',
      intro: 'Die ersten Stunden: Passkontrolle, Taxi, Einchecken im Hotel. Kurze, höfliche, klare Sätze.',
      words: [
        { w: 'die Passkontrolle', tr: 'controllo passaporti', def: 'Ort, an dem der Pass geprüft wird.', ex: 'Die Passkontrolle ging sehr schnell.', g: 'f', pl: 'die Passkontrollen' },
        { w: 'die Bordkarte', tr: 'carta d\'imbarco', def: 'Dokument, um ins Flugzeug zu steigen.', ex: 'Ihre Bordkarte, bitte.', g: 'f', pl: 'die Bordkarten' },
        { w: 'das Gepäck', tr: 'bagagli', def: 'Koffer und Taschen.', ex: 'Mein Gepäck ist nicht angekommen.', g: 'n', pl: '—' },
        { w: 'der Zweck der Reise', tr: 'scopo del viaggio', def: 'Warum man reist.', ex: 'Was ist der Zweck Ihrer Reise?', g: 'm', pl: '—' },
        { w: 'die Reservierung', tr: 'prenotazione', def: 'Ein gebuchtes Zimmer.', ex: 'Ich habe eine Reservierung auf den Namen Rossi.', g: 'f', pl: 'die Reservierungen' },
        { w: 'die Quittung', tr: 'ricevuta', def: 'Beleg für eine Zahlung.', ex: 'Kann ich bitte eine Quittung bekommen?', g: 'f', pl: 'die Quittungen' },
      ],
      expr: [
        { p: 'Ich bin beruflich hier.', n: 'Antwort bei der Passkontrolle.' },
        { p: 'Ich bleibe sechs Monate.', n: '' },
        { p: 'Können Sie mich bitte zu dieser Adresse bringen?', n: '' },
        { p: 'Was kostet das ungefähr?', n: '' },
        { p: 'Ich habe eine Reservierung auf den Namen Rossi.', n: '' },
        { p: 'Ab wann gibt es Frühstück?', n: '' },
      ],
      col: [{ p: 'das Gepäck abholen', n: '' }, { p: 'ein Formular ausfüllen', n: '' }, { p: 'ein Taxi nehmen', n: '' }],
      scen: [{ p: 'Beantworten Sie bei der Passkontrolle die Fragen und checken Sie dann im Hotel ein.', mode: 'speak', keys: ['Ich bin beruflich hier', 'Ich bleibe', 'Ich habe eine Reservierung'], model: 'Guten Morgen. Ich bin beruflich hier. Ich fange an der Uniklinik an. Ich bleibe sechs Monate. Hier ist mein Arbeitsvertrag. Danke. Guten Tag, ich habe eine Reservierung auf den Namen Rossi. Ab wann gibt es Frühstück?' }],
    },
    {
      id: 'de-abr-erstewoche', cat: 'firstweek', title: 'Die erste Woche: sich vorstellen, Anweisungen, nachfragen', l: 'B1', icon: 'user',
      intro: 'Der Start im neuen Job: sich vorstellen, Anweisungen verstehen und ohne Scheu nachfragen.',
      words: [
        { w: 'die Einarbeitung', tr: 'periodo di inserimento', def: 'Die Zeit, in der man in den Job eingeführt wird.', ex: 'Die Einarbeitung dauert zwei Wochen.', g: 'f', pl: 'die Einarbeitungen' },
        { w: 'die Vorgesetzte', tr: 'la superiore, responsabile', def: 'Die Person, der man berichtet.', ex: 'Meine Vorgesetzte zeigt mir die Station.', g: 'f', pl: 'die Vorgesetzten' },
        { w: 'der Dienstausweis', tr: 'badge', def: 'Ausweis für den Arbeitsplatz.', ex: 'Mit dem Dienstausweis öffnen Sie die Tür.', g: 'm', pl: 'die Dienstausweise' },
        { w: 'die Schicht', tr: 'turno', def: 'Eine Arbeitsperiode.', ex: 'Meine erste Schicht beginnt um acht.', g: 'f', pl: 'die Schichten' },
        { w: 'nachfragen', tr: 'chiedere chiarimenti', def: 'Noch einmal fragen, wenn etwas unklar ist.', ex: 'Fragen Sie ruhig nach.' },
        { w: 'sich einarbeiten', tr: 'ambientarsi nel lavoro', def: 'Lernen, wie die Arbeit funktioniert.', ex: 'Sie werden sich schnell einarbeiten.' },
      ],
      expr: [
        { p: 'Hallo, ich bin neu hier und habe gerade im Team angefangen.', n: '' },
        { p: 'Entschuldigung, können Sie das bitte langsamer wiederholen?', n: 'Nachfragen ist normal und höflich.' },
        { p: 'Habe ich das richtig verstanden: Zuerst melde ich mich an, dann drucke ich die Liste?', n: 'Verständnis prüfen.' },
        { p: 'Wofür steht diese Abkürzung?', n: '' },
        { p: 'An wen kann ich mich wenden, wenn ich ein Problem habe?', n: '' },
        { p: 'Danke, das hilft mir sehr.', n: '' },
      ],
      col: [{ p: 'eine Anweisung befolgen', n: '' }, { p: 'eine neue Stelle antreten', n: '' }, { p: 'sich an jemanden wenden', n: '' }],
      scen: [{ p: 'Ihr erster Tag: Stellen Sie sich einer Kollegin vor und prüfen Sie, ob Sie die Anweisungen verstanden haben.', mode: 'speak', keys: ['ich bin neu hier', 'langsamer wiederholen', 'Habe ich das richtig verstanden'], model: 'Hallo, ich bin neu hier und habe gerade im Team angefangen. Ich heiße Luca. Entschuldigung, können Sie das bitte langsamer wiederholen? Habe ich das richtig verstanden: Zuerst melde ich mich an, dann drucke ich die Liste? An wen kann ich mich wenden, wenn ich ein Problem habe? Danke, das hilft mir sehr.' }],
    },
    {
      id: 'de-abr-wohnung', cat: 'daily', title: 'Eine Wohnung mieten, mit dem Vermieter sprechen', l: 'B1', icon: 'clipboard',
      intro: 'Eine Wohnung besichtigen, nach dem Vertrag fragen, dem Vermieter ein Problem melden.',
      words: [
        { w: 'der Vermieter', tr: 'padrone di casa', def: 'Person, die die Wohnung vermietet.', ex: 'Ich muss den Vermieter wegen der Heizung anrufen.', g: 'm', pl: 'die Vermieter' },
        { w: 'die Kaution', tr: 'deposito cauzionale', def: 'Geld, das man am Anfang zahlt und später zurückbekommt.', ex: 'Die Kaution beträgt drei Monatsmieten.', g: 'f', pl: 'die Kautionen' },
        { w: 'die Nebenkosten', tr: 'spese accessorie', def: 'Kosten für Heizung, Wasser, Müll.', ex: 'Sind die Nebenkosten in der Miete enthalten?', g: 'f', pl: '(Plural)' },
        { w: 'der Mietvertrag', tr: 'contratto d\'affitto', def: 'Vertrag über die Miete.', ex: 'Der Mietvertrag ist unbefristet.', g: 'm', pl: 'die Mietverträge' },
        { w: 'möbliert', tr: 'arredato', def: 'Mit Möbeln.', ex: 'Ist die Wohnung möbliert?' },
        { w: 'kaputt', tr: 'rotto', def: 'Funktioniert nicht.', ex: 'Die Heizung ist kaputt.' },
      ],
      expr: [
        { p: 'Sind die Nebenkosten in der Miete enthalten?', n: 'Warmmiete = mit Nebenkosten, Kaltmiete = ohne.' },
        { p: 'Wie lange läuft der Mietvertrag?', n: '' },
        { p: 'Ab wann könnte ich einziehen?', n: '' },
        { p: 'Ich rufe wegen eines Problems in der Wohnung an.', n: 'wegen + Genitiv.' },
        { p: 'Könnten Sie bitte jemanden vorbeischicken?', n: '' },
      ],
      col: [{ p: 'die Miete zahlen', n: '' }, { p: 'den Mietvertrag unterschreiben', n: '' }, { p: 'einen Schaden melden', n: '' }],
      scen: [{ p: 'Rufen Sie den Vermieter an: Die Heizung funktioniert nicht. Erklären Sie das Problem und fragen Sie, wann jemand kommen kann.', mode: 'speak', keys: ['Ich rufe wegen', 'jemanden vorbeischicken', 'funktioniert nicht'], model: 'Guten Tag, hier ist Luca aus der Wohnung im vierten Stock. Ich rufe wegen eines Problems in der Wohnung an. Die Heizung funktioniert seit gestern Abend nicht, und es ist sehr kalt. Könnten Sie bitte jemanden vorbeischicken? Ich bin ab sechs Uhr zu Hause.' }],
    },
    {
      id: 'de-abr-bank', cat: 'daily', title: 'Bank, Unterlagen und Behörden', l: 'B1', icon: 'briefcase',
      intro: 'Ein Konto eröffnen, sich anmelden und wissen, welche Unterlagen man braucht.',
      words: [
        { w: 'ein Konto eröffnen', tr: 'aprire un conto', def: 'Ein neues Bankkonto anlegen.', ex: 'Ich möchte ein Konto eröffnen.' },
        { w: 'die Anmeldung', tr: 'iscrizione anagrafica', def: 'Registrierung des Wohnsitzes beim Amt.', ex: 'Für die Anmeldung brauchen Sie die Wohnungsgeberbestätigung.', g: 'f', pl: 'die Anmeldungen' },
        { w: 'die Bankkarte', tr: 'bancomat', def: 'Karte für das Bankkonto.', ex: 'Die Bankkarte kommt per Post.', g: 'f', pl: 'die Bankkarten' },
        { w: 'der Termin', tr: 'appuntamento', def: 'Vereinbarte Zeit.', ex: 'Brauche ich einen Termin?', g: 'm', pl: 'die Termine' },
        { w: 'das Formular', tr: 'modulo', def: 'Ein Dokument zum Ausfüllen.', ex: 'Bitte füllen Sie dieses Formular aus.', g: 'n', pl: 'die Formulare' },
        { w: 'die Überweisung', tr: 'bonifico', def: 'Geld von einem Konto auf ein anderes schicken.', ex: 'Ich muss eine Überweisung nach Italien machen.', g: 'f', pl: 'die Überweisungen' },
      ],
      expr: [
        { p: 'Welche Unterlagen brauche ich?', n: '' },
        { p: 'Ich bin gerade beruflich hierhergezogen.', n: '' },
        { p: 'Wie lange dauert das?', n: '' },
        { p: 'Kostet das eine Gebühr?', n: '' },
        { p: 'Könnten Sie mir das bitte aufschreiben?', n: '' },
      ],
      col: [{ p: 'ein Formular ausfüllen', n: '' }, { p: 'eine Überweisung machen', n: '' }, { p: 'einen Termin vereinbaren', n: '' }],
      scen: [{ p: 'Eröffnen Sie bei der Bank ein Konto. Erklären Sie Ihre Situation und fragen Sie nach den Unterlagen.', mode: 'speak', keys: ['ein Konto eröffnen', 'Welche Unterlagen brauche ich', 'beruflich'], model: 'Guten Tag. Ich möchte ein Konto eröffnen. Ich bin gerade beruflich hierhergezogen. Welche Unterlagen brauche ich? Ich habe meinen Pass und meinen Arbeitsvertrag, aber die Anmeldung habe ich noch nicht. Wie lange dauert das? Kostet die Bankkarte eine Gebühr?' }],
    },
    {
      id: 'de-abr-gesundheit', cat: 'daily', title: 'Als Patient: Hausarzt, Apotheke', l: 'B1', icon: 'heart',
      intro: 'Einen Termin beim Hausarzt machen, ein Problem beschreiben, in der Apotheke Medikamente kaufen.',
      words: [
        { w: 'die Hausarztpraxis', tr: 'ambulatorio del medico di base', def: 'Praxis eines Allgemeinarztes.', ex: 'Die Hausarztpraxis öffnet um acht.', g: 'f', pl: 'die Hausarztpraxen' },
        { w: 'die Krankenversicherungskarte', tr: 'tessera sanitaria', def: 'Karte der Krankenkasse.', ex: 'Haben Sie Ihre Krankenversicherungskarte dabei?', g: 'f', pl: 'die Krankenversicherungskarten' },
        { w: 'die Beschwerden', tr: 'disturbi, sintomi', def: 'Gesundheitliche Probleme.', ex: 'Welche Beschwerden haben Sie?', g: 'f', pl: '(Plural)' },
        { w: 'die Apothekerin', tr: 'farmacista', def: 'Fachfrau in der Apotheke.', ex: 'Fragen Sie die Apothekerin.', g: 'f', pl: 'die Apothekerinnen' },
        { w: 'rezeptfrei', tr: 'senza ricetta', def: 'Ohne ärztliches Rezept erhältlich.', ex: 'Das gibt es rezeptfrei.' },
        { w: 'die Halsschmerzen', tr: 'mal di gola', def: 'Schmerzen im Hals.', ex: 'Ich habe seit drei Tagen Halsschmerzen.', g: 'f', pl: '(Plural)' },
      ],
      expr: [
        { p: 'Ich hätte gern einen Termin beim Hausarzt.', n: '' },
        { p: 'Ich habe seit drei Tagen Halsschmerzen.', n: 'seit + Dativ, Präsens.' },
        { p: 'Gibt es dafür etwas Rezeptfreies?', n: '' },
        { p: 'Wie oft soll ich das nehmen?', n: '' },
        { p: 'Kann ich das zusammen mit meinen anderen Medikamenten nehmen?', n: '' },
      ],
      col: [{ p: 'einen Termin machen', n: '' }, { p: 'eine Tablette nehmen', n: '' }, { p: 'sich besser fühlen', n: '' }],
      scen: [{ p: 'Beschreiben Sie in der Apotheke Ihre Beschwerden und fragen Sie, was Sie nehmen können und wie oft.', mode: 'speak', keys: ['seit drei Tagen', 'Rezeptfreies', 'Wie oft'], model: 'Guten Tag. Ich habe seit drei Tagen Halsschmerzen und bin etwas müde. Fieber habe ich nicht. Gibt es dafür etwas Rezeptfreies? Wie oft soll ich das nehmen? Kann ich das zusammen mit meinen anderen Medikamenten nehmen?' }],
    },
    {
      id: 'de-abr-alltag', cat: 'daily', title: 'Einkaufen und öffentlicher Verkehr', l: 'A2', icon: 'map',
      intro: 'Einkaufen, nach dem Weg fragen, Fahrkarten und Fahrpläne.',
      words: [
        { w: 'die Fahrkarte', tr: 'biglietto', def: 'Ticket für Bus oder Bahn.', ex: 'Wo kann ich eine Fahrkarte kaufen?', g: 'f', pl: 'die Fahrkarten' },
        { w: 'das Gleis', tr: 'binario', def: 'Ort, an dem der Zug abfährt.', ex: 'Der Zug fährt von Gleis vier.', g: 'n', pl: 'die Gleise' },
        { w: 'umsteigen', tr: 'cambiare (mezzo)', def: 'Von einem Zug in einen anderen wechseln.', ex: 'Muss ich umsteigen?' },
        { w: 'das Regal', tr: 'scaffale', def: 'Möbel für Waren im Geschäft.', ex: 'Der Reis steht im Regal hinten links.', g: 'n', pl: 'die Regale' },
        { w: 'umtauschen', tr: 'cambiare un prodotto', def: 'Etwas zurückgeben und etwas anderes bekommen.', ex: 'Kann ich das umtauschen?' },
        { w: 'die Monatskarte', tr: 'abbonamento mensile', def: 'Fahrkarte für einen Monat.', ex: 'Eine Monatskarte lohnt sich.', g: 'f', pl: 'die Monatskarten' },
      ],
      expr: [
        { p: 'Entschuldigung, welcher Bus fährt zum Krankenhaus?', n: '' },
        { p: 'Muss ich umsteigen?', n: '' },
        { p: 'Wo finde ich den Reis?', n: '' },
        { p: 'Kann ich mit Karte zahlen?', n: 'In Deutschland ist Bargeld noch häufig.' },
        { p: 'Ich möchte das bitte umtauschen.', n: '' },
      ],
      col: [{ p: 'den Bus nehmen', n: '' }, { p: 'den Zug verpassen', n: '' }, { p: 'mit Karte zahlen', n: '' }],
      scen: [{ p: 'Kaufen Sie am Bahnhof eine Fahrkarte und fragen Sie, von welchem Gleis der Zug fährt und ob Sie umsteigen müssen.', mode: 'speak', keys: ['Fahrkarte', 'Muss ich umsteigen', 'Gleis'], model: 'Guten Tag, eine Fahrkarte in die Innenstadt, hin und zurück, bitte. Kann ich mit Karte zahlen? Von welchem Gleis fährt der Zug? Muss ich umsteigen? Danke. Und wann fährt der letzte Zug zurück?' }],
    },
    {
      id: 'de-abr-arbeit', cat: 'workplace', title: 'Bei der Arbeit: Small Talk, Besprechungen, um Hilfe bitten', l: 'B1', icon: 'users',
      intro: 'Alltägliche Kommunikation im Job: Small Talk, eine Meinung sagen, höflich widersprechen, um Hilfe bitten.',
      words: [
        { w: 'der Small Talk', tr: 'chiacchiere di cortesia', def: 'Leichte Unterhaltung.', ex: 'Small Talk in der Kaffeeküche ist wichtig.', g: 'm', pl: '—' },
        { w: 'sich austauschen', tr: 'confrontarsi', def: 'Informationen und Meinungen teilen.', ex: 'Lass uns nach der Besprechung kurz austauschen.' },
        { w: 'die Sichtweise', tr: 'punto di vista', def: 'Eine Meinung.', ex: 'Ich verstehe Ihre Sichtweise, aber…', g: 'f', pl: 'die Sichtweisen' },
        { w: 'die Frist', tr: 'scadenza', def: 'Zeitpunkt, bis wann etwas fertig sein muss.', ex: 'Die Frist endet am Freitag.', g: 'f', pl: 'die Fristen' },
        { w: 'jemandem helfen', tr: 'aiutare qualcuno', def: 'helfen + Dativ.', ex: 'Kannst du mir kurz helfen?' },
        { w: 'sich verspäten', tr: 'essere in ritardo', def: 'Später kommen als geplant.', ex: 'Entschuldigung, ich verspäte mich.' },
      ],
      expr: [
        { p: 'Wie war dein Wochenende?', n: 'Unter Kollegen oft du.' },
        { p: 'Meiner Meinung nach sollten wir mit den dringenden Fällen anfangen.', n: 'Verb an Position zwei.' },
        { p: 'Ich verstehe, was du meinst, aber ich bin mir nicht sicher, ob das funktioniert.', n: 'Höflich widersprechen.' },
        { p: 'Kannst du mir kurz helfen?', n: '' },
        { p: 'Darf ich kurz etwas ergänzen?', n: 'Höflich unterbrechen.' },
      ],
      col: [{ p: 'eine Frist einhalten', n: '' }, { p: 'einen Punkt ansprechen', n: '' }, { p: 'einen Vorschlag machen', n: '' }],
      scen: [{ p: 'Sagen Sie in der Teambesprechung Ihre Meinung zum neuen Dienstplan und widersprechen Sie höflich einem Kollegen.', mode: 'speak', keys: ['Meiner Meinung nach', 'Ich verstehe, was du meinst', 'Darf ich kurz etwas ergänzen'], model: 'Darf ich kurz etwas ergänzen? Meiner Meinung nach ist der neue Dienstplan eine gute Idee, aber wir sollten mit den Wochenenddiensten anfangen. Ich verstehe, was du meinst, aber ich bin mir nicht sicher, ob das mit weniger Personal in der Nacht funktioniert. Vielleicht testen wir es einen Monat und besprechen es dann noch einmal.' }],
    },
    {
      id: 'de-abr-sozial', cat: 'social', social: true, title: 'Soziales Leben: Freunde, Einladungen, Pläne', l: 'B1', icon: 'message',
      intro: 'Freunde finden, Einladungen annehmen und absagen, Pläne machen, lockere Gespräche.',
      words: [
        { w: 'Lust haben', tr: 'avere voglia', def: 'Etwas gern tun wollen.', ex: 'Hast du Lust auf einen Kaffee?' },
        { w: 'sich treffen', tr: 'incontrarsi', def: 'Zusammenkommen.', ex: 'Wollen wir uns am Samstag treffen?' },
        { w: 'absagen', tr: 'disdire, declinare', def: 'Sagen, dass man nicht kommt.', ex: 'Ich muss leider absagen.' },
        { w: 'etwas trinken gehen', tr: 'andare a bere qualcosa', def: 'In eine Bar gehen.', ex: 'Gehen wir nach der Arbeit etwas trinken?' },
        { w: 'mitbringen', tr: 'portare (con sé)', def: 'Etwas zu einer Einladung bringen.', ex: 'Soll ich etwas mitbringen?' },
        { w: 'passen', tr: 'andare bene (orario)', def: 'Zeitlich gut sein.', ex: 'Passt dir Donnerstag?' },
      ],
      expr: [
        { p: 'Hast du Lust, nach der Arbeit etwas trinken zu gehen?', n: '' },
        { p: 'Sehr gern, aber am Samstag arbeite ich leider.', n: 'Höflich absagen.' },
        { p: 'Wie wäre es nächste Woche?', n: '' },
        { p: 'Soll ich etwas mitbringen?', n: '' },
        { p: 'Sag einfach Bescheid, wann es dir passt.', n: '' },
      ],
      col: [{ p: 'Pläne machen', n: '' }, { p: 'eine Einladung annehmen', n: '' }, { p: 'Spaß haben', n: '' }],
      scen: [{ p: 'Eine Kollegin lädt Sie ein. Sagen Sie für Samstag höflich ab und schlagen Sie einen anderen Tag vor.', mode: 'speak', keys: ['Sehr gern, aber', 'Wie wäre es', 'Sag einfach Bescheid'], model: 'Danke für die Einladung! Sehr gern, aber am Samstag arbeite ich leider. Wie wäre es nächste Woche? Am Donnerstagabend habe ich Zeit. Soll ich etwas mitbringen? Sag einfach Bescheid, wann es dir passt.' }],
    },
  ];
  LOS.lang.register({ code: 'de', abroad });
})();
