/* English — Life Abroad track: functioning in another country, from arrival to social life. */
(function () {
  'use strict';
  const LOS = window.LOS;
  const abroad = [
    {
      id: 'en-abr-arrival', cat: 'arrival', title: 'Arrival: airport, immigration, taxi, hotel', l: 'A2', icon: 'globe',
      intro: 'The first hours: passport control, getting a taxi, checking in. Short, polite, clear sentences.',
      words: [
        { w: 'passport control', tr: 'controllo passaporti', def: 'Where officers check your passport.', ex: 'Passport control was very quick.' },
        { w: 'boarding pass', tr: 'carta d\'imbarco', def: 'The document you need to get on the plane.', ex: 'Can I see your boarding pass, please?' },
        { w: 'luggage', tr: 'bagagli', def: 'Bags and suitcases (uncountable).', ex: 'My luggage has not arrived.' },
        { w: 'purpose of your visit', tr: 'motivo della visita', def: 'Why you are travelling.', ex: 'What is the purpose of your visit?' },
        { w: 'check in', tr: 'fare il check-in', def: 'To register at a hotel or airport.', ex: 'I would like to check in, please.' },
        { w: 'booking', tr: 'prenotazione', def: 'A reservation.', ex: 'I have a booking under the name Rossi.' },
        { w: 'receipt', tr: 'ricevuta', def: 'A paper that shows you have paid.', ex: 'Could I have a receipt, please?' },
      ],
      expr: [
        { p: 'I am here for work.', n: 'Answer at immigration.' },
        { p: 'I will be staying for six months.', n: '' },
        { p: 'Could you take me to this address, please?', n: '' },
        { p: 'How much will it be, roughly?', n: '' },
        { p: 'I have a booking under the name Rossi.', n: '' },
        { p: 'What time is breakfast?', n: '' },
      ],
      col: [{ p: 'collect your luggage', n: '' }, { p: 'fill in a form', n: 'Not "compile a form".' }, { p: 'take a taxi', n: '' }],
      scen: [{ p: 'At immigration, answer the officer\'s questions; then check in at your hotel.', mode: 'speak', keys: ['I am here for work', 'I will be staying', 'I have a booking'], model: 'Good morning. I am here for work. I am starting a job at the city hospital. I will be staying for six months. Here is my contract. Thank you. Hello, I have a booking under the name Rossi. I would like to check in, please. What time is breakfast?' }],
    },
    {
      id: 'en-abr-firstweek', cat: 'firstweek', title: 'First week: introducing yourself, instructions, clarification', l: 'B1', icon: 'user',
      intro: 'Starting a new job: introduce yourself, understand instructions, and ask for clarification without embarrassment.',
      words: [
        { w: 'induction', tr: 'formazione iniziale / inserimento', def: 'Training for new staff (UK).', ex: 'My induction starts on Monday.' },
        { w: 'line manager', tr: 'responsabile diretto', def: 'The person you report to (UK).', ex: 'My line manager will show me around.' },
        { w: 'badge', tr: 'badge, tesserino', def: 'An ID card for the building.', ex: 'You need your badge to open the door.' },
        { w: 'shift', tr: 'turno', def: 'A period of work.', ex: 'My first shift starts at eight.' },
        { w: 'show someone around', tr: 'far fare il giro a qualcuno', def: 'To give a tour.', ex: 'Let me show you around.' },
        { w: 'get the hang of it', tr: 'prenderci la mano', def: 'To learn how to do something (informal).', ex: 'You will get the hang of it quickly.' },
      ],
      expr: [
        { p: 'Hi, I am new here. I have just started in the team.', n: '' },
        { p: 'Sorry, could you say that again more slowly?', n: 'Asking for clarification is normal and polite.' },
        { p: 'Just to check I have understood: first I log in, then I print the list?', n: 'Check understanding by summarising.' },
        { p: 'What does that abbreviation stand for?', n: '' },
        { p: 'Who should I ask if I have a problem?', n: '' },
        { p: 'Thanks, that is really helpful.', n: '' },
      ],
      col: [{ p: 'ask for clarification', n: '' }, { p: 'follow instructions', n: '' }, { p: 'start a new job', n: '' }],
      scen: [{ p: 'Your first day: introduce yourself to a colleague, then check that you have understood the instructions.', mode: 'speak', keys: ['I am new here', 'could you say that again', 'Just to check'], model: 'Hi, I am new here. I am Luca, and I have just started in the team. Sorry, could you say that again more slowly? Just to check I have understood: first I log in, then I print the list for the morning? And who should I ask if I have a problem? Thanks, that is really helpful.' }],
    },
    {
      id: 'en-abr-housing', cat: 'daily', title: 'Renting a flat and talking to the landlord', l: 'B1', icon: 'clipboard',
      intro: 'Viewing a flat, asking about the contract, reporting a problem to the landlord.',
      words: [
        { w: 'landlord', tr: 'padrone di casa', def: 'The person who rents a flat to you.', ex: 'I need to call the landlord about the heating.' },
        { w: 'deposit', tr: 'deposito cauzionale', def: 'Money you pay at the start and get back later.', ex: 'The deposit is one month\'s rent.' },
        { w: 'bills', tr: 'bollette', def: 'Payments for gas, electricity, water.', ex: 'Are the bills included in the rent?' },
        { w: 'lease', tr: 'contratto d\'affitto', def: 'The rental contract.', ex: 'The lease is for twelve months.' },
        { w: 'furnished', tr: 'arredato', def: 'With furniture.', ex: 'Is the flat furnished?' },
        { w: 'leak', tr: 'perdita (d\'acqua)', def: 'Water coming out where it should not.', ex: 'There is a leak under the sink.' },
      ],
      expr: [
        { p: 'Are the bills included in the rent?', n: '' },
        { p: 'How long is the lease?', n: '' },
        { p: 'When could I move in?', n: '' },
        { p: 'I am calling about a problem in the flat.', n: '' },
        { p: 'Could you send someone to have a look?', n: '' },
      ],
      col: [{ p: 'pay the rent', n: '' }, { p: 'sign the lease', n: '' }, { p: 'report a problem', n: '' }],
      scen: [{ p: 'Call your landlord: the heating is not working. Explain the problem and ask when someone can come.', mode: 'speak', keys: ['I am calling about', 'Could you send someone', 'not working'], model: 'Hello, this is Luca from flat 4. I am calling about a problem in the flat. The heating has not been working since yesterday evening, and it is very cold. Could you send someone to have a look? I am at home after six. When could someone come?' }],
    },
    {
      id: 'en-abr-bank', cat: 'daily', title: 'Bank, documents and paperwork', l: 'B1', icon: 'briefcase',
      intro: 'Opening a bank account, registering, understanding what documents you need.',
      words: [
        { w: 'open an account', tr: 'aprire un conto', def: 'To start a bank account.', ex: 'I would like to open an account.' },
        { w: 'proof of address', tr: 'prova di residenza', def: 'A document showing where you live.', ex: 'Do you have proof of address?' },
        { w: 'debit card', tr: 'carta di debito/bancomat', def: 'A card that takes money from your account.', ex: 'Your debit card will arrive by post.' },
        { w: 'appointment', tr: 'appuntamento', def: 'An arranged meeting.', ex: 'Do I need an appointment?' },
        { w: 'form', tr: 'modulo', def: 'A document with questions to complete.', ex: 'Please fill in this form.' },
        { w: 'transfer', tr: 'bonifico', def: 'Moving money between accounts.', ex: 'I need to make a transfer to Italy.' },
      ],
      expr: [
        { p: 'What documents do I need?', n: '' },
        { p: 'I have just moved here for work.', n: '' },
        { p: 'How long does it take?', n: '' },
        { p: 'Is there a fee for that?', n: '' },
        { p: 'Could you write that down for me?', n: '' },
      ],
      col: [{ p: 'fill in a form', n: '' }, { p: 'make a transfer', n: '' }, { p: 'book an appointment', n: '' }],
      scen: [{ p: 'At the bank: open an account. Explain your situation and ask what documents you need.', mode: 'speak', keys: ['open an account', 'What documents do I need', 'proof of address'], model: 'Hello. I would like to open an account. I have just moved here for work. What documents do I need? I have my passport and my contract, but I do not have proof of address yet. How long does it take? Is there a fee for the debit card?' }],
    },
    {
      id: 'en-abr-health', cat: 'daily', title: 'Healthcare as a patient: GP, pharmacy', l: 'B1', icon: 'heart',
      intro: 'Registering with a doctor, describing a problem, buying medicine at the pharmacy.',
      words: [
        { w: 'register with a GP', tr: 'iscriversi dal medico di base', def: 'To join a family doctor\'s practice (UK).', ex: 'You should register with a GP soon.' },
        { w: 'surgery', tr: 'ambulatorio (UK)', def: 'A doctor\'s practice in British English.', ex: 'The surgery opens at eight.' },
        { w: 'symptoms', tr: 'sintomi', def: 'Signs of an illness.', ex: 'What are your symptoms?' },
        { w: 'pharmacist', tr: 'farmacista', def: 'A person who sells and advises on medicine.', ex: 'Ask the pharmacist for advice.' },
        { w: 'over the counter', tr: 'da banco', def: 'Without a prescription.', ex: 'You can buy it over the counter.' },
        { w: 'sore throat', tr: 'mal di gola', def: 'Pain in the throat.', ex: 'I have had a sore throat for three days.' },
      ],
      expr: [
        { p: 'I would like to register with the surgery.', n: '' },
        { p: 'I have had a sore throat for three days.', n: 'Present perfect for duration.' },
        { p: 'Can I get something for this over the counter?', n: '' },
        { p: 'How often should I take it?', n: '' },
        { p: 'Is it OK to take it with my other medication?', n: '' },
      ],
      col: [{ p: 'make an appointment', n: '' }, { p: 'take a tablet', n: '' }, { p: 'feel better', n: '' }],
      scen: [{ p: 'At the pharmacy: describe your symptoms and ask what you can take and how often.', mode: 'speak', keys: ['I have had', 'over the counter', 'How often'], model: 'Hello. I have had a sore throat for three days, and I feel a bit tired. I do not have a fever. Can I get something for this over the counter? How often should I take it? Is it OK to take it with my other medication?' }],
    },
    {
      id: 'en-abr-daily', cat: 'daily', title: 'Shopping and public transport', l: 'A2', icon: 'map',
      intro: 'Buying things, asking for directions, tickets and timetables.',
      words: [
        { w: 'return ticket', tr: 'biglietto di andata e ritorno', def: 'A ticket to go and come back (UK).', ex: 'A return ticket to the city centre, please.' },
        { w: 'platform', tr: 'binario', def: 'Where you get on the train.', ex: 'The train leaves from platform 4.' },
        { w: 'top up', tr: 'ricaricare', def: 'To add money to a card.', ex: 'I need to top up my travel card.' },
        { w: 'aisle', tr: 'corsia (supermercato)', def: 'A passage between shelves.', ex: 'The rice is in aisle six.' },
        { w: 'refund', tr: 'rimborso', def: 'Money given back.', ex: 'Can I get a refund?' },
        { w: 'change', tr: 'resto; cambio (treno)', def: 'Money returned, or changing trains.', ex: 'Do I need to change trains?' },
      ],
      expr: [
        { p: 'Excuse me, which bus goes to the hospital?', n: '' },
        { p: 'Do I need to change?', n: '' },
        { p: 'Where can I find the rice?', n: '' },
        { p: 'Can I pay by card?', n: '' },
        { p: 'I would like to return this, please.', n: '' },
      ],
      col: [{ p: 'catch the bus', n: '' }, { p: 'miss the train', n: '' }, { p: 'pay by card', n: 'Not "pay with card".' }],
      scen: [{ p: 'At the station: buy a ticket, ask where the train leaves from and whether you need to change.', mode: 'speak', keys: ['return ticket', 'Do I need to change', 'platform'], model: 'Hello, a return ticket to the city centre, please. Can I pay by card? Which platform does it leave from? Do I need to change? Thank you. And what time is the last train back?' }],
    },
    {
      id: 'en-abr-work', cat: 'workplace', title: 'At work: small talk, meetings, asking for help', l: 'B1', icon: 'users',
      intro: 'Everyday workplace interaction: small talk, giving an opinion, disagreeing politely, asking for help.',
      words: [
        { w: 'small talk', tr: 'chiacchiere di cortesia', def: 'Light conversation about everyday topics.', ex: 'Small talk is important in British offices.' },
        { w: 'catch up', tr: 'aggiornarsi', def: 'To exchange news.', ex: 'Shall we catch up after the meeting?' },
        { w: 'point of view', tr: 'punto di vista', def: 'An opinion.', ex: 'I see your point of view, but…' },
        { w: 'deadline', tr: 'scadenza', def: 'The time by which something must be done.', ex: 'The deadline is on Friday.' },
        { w: 'give someone a hand', tr: 'dare una mano', def: 'To help (informal).', ex: 'Could you give me a hand with this?' },
        { w: 'run late', tr: 'essere in ritardo', def: 'To be behind schedule.', ex: 'Sorry, I am running late.' },
      ],
      expr: [
        { p: 'How was your weekend?', n: 'Classic small talk.' },
        { p: 'In my opinion, we should start with the urgent cases.', n: '' },
        { p: 'I see what you mean, but I am not sure that will work.', n: 'Polite disagreement.' },
        { p: 'Sorry, could you give me a hand with this?', n: '' },
        { p: 'Could I just add something?', n: 'Interrupting politely.' },
      ],
      col: [{ p: 'meet a deadline', n: '' }, { p: 'raise a point', n: '' }, { p: 'make a suggestion', n: '' }],
      scen: [{ p: 'In a team meeting, give your opinion on a new rota and disagree politely with a colleague.', mode: 'speak', keys: ['In my opinion', 'I see what you mean', 'Could I just add something'], model: 'Could I just add something? In my opinion, the new rota is a good idea, but we should start with the weekend shifts. I see what you mean about the costs, but I am not sure that will work if we have fewer staff at night. Maybe we could try it for one month and then review it.' }],
    },
    {
      id: 'en-abr-social', cat: 'social', social: true, title: 'Social life: friends, invitations, plans', l: 'B1', icon: 'message',
      intro: 'Making friends, accepting and declining invitations, making plans, informal conversation and humour.',
      words: [
        { w: 'fancy', tr: 'avere voglia di (UK, informale)', def: 'To want to do something.', ex: 'Do you fancy a coffee?' },
        { w: 'hang out', tr: 'uscire insieme', def: 'To spend time together (informal).', ex: 'We usually hang out in the park.' },
        { w: 'rain check', tr: 'rimandare a un\'altra volta', def: 'A polite way to postpone (US, informal).', ex: 'Can I take a rain check?' },
        { w: 'up for', tr: 'disposto a, in vena di', def: 'Willing to do something (informal).', ex: 'Are you up for a walk on Sunday?' },
        { w: 'get together', tr: 'ritrovarsi', def: 'To meet socially.', ex: 'Let\'s get together next week.' },
        { w: 'bring something', tr: 'portare qualcosa', def: 'To take something with you to someone\'s home.', ex: 'Shall I bring something?' },
      ],
      expr: [
        { p: 'Do you fancy a drink after work?', n: '' },
        { p: 'I would love to, but I am working on Saturday.', n: 'Declining politely.' },
        { p: 'How about next week instead?', n: '' },
        { p: 'Shall I bring something?', n: 'When invited to someone\'s home.' },
        { p: 'Let me know when suits you.', n: '' },
      ],
      col: [{ p: 'make plans', n: '' }, { p: 'turn down an invitation', n: '' }, { p: 'have a laugh', n: 'informal' }],
      scen: [{ p: 'A colleague invites you out. Decline politely for Saturday and suggest another day.', mode: 'speak', keys: ['I would love to, but', 'How about', 'Let me know'], model: 'Thanks for asking! I would love to, but I am working on Saturday. How about next week instead? I am free on Thursday evening. Shall I bring something? Let me know when suits you.' }],
    },
  ];
  LOS.lang.register({ code: 'en', abroad });
})();
