/* Español — Vivir en el extranjero: desde la llegada hasta la vida social. */
(function () {
  'use strict';
  const LOS = window.LOS;
  const abroad = [
    {
      id: 'es-abr-llegada', cat: 'arrival', title: 'La llegada: aeropuerto, control, taxi, hotel', l: 'A2', icon: 'globe',
      intro: 'Las primeras horas: control de pasaportes, taxi y registro en el hotel. Frases cortas, claras y educadas.',
      words: [
        { w: 'el control de pasaportes', tr: 'controllo passaporti', def: 'Lugar donde revisan el pasaporte.', ex: 'El control de pasaportes fue muy rápido.', g: 'm', pl: 'los controles de pasaportes' },
        { w: 'la tarjeta de embarque', tr: 'carta d\'imbarco', def: 'Documento para subir al avión.', ex: '¿Me enseña la tarjeta de embarque, por favor?', g: 'f', pl: 'las tarjetas de embarque' },
        { w: 'el equipaje', tr: 'bagagli', def: 'Maletas y bolsas de viaje.', ex: 'Mi equipaje no ha llegado.', g: 'm', pl: '—' },
        { w: 'el motivo del viaje', tr: 'motivo del viaggio', def: 'Por qué viaja.', ex: '¿Cuál es el motivo del viaje?', g: 'm', pl: '—' },
        { w: 'la reserva', tr: 'prenotazione', def: 'Habitación o plaza reservada.', ex: 'Tengo una reserva a nombre de Rossi.', g: 'f', pl: 'las reservas' },
        { w: 'el recibo', tr: 'ricevuta', def: 'Papel que demuestra un pago.', ex: '¿Me puede dar un recibo, por favor?', g: 'm', pl: 'los recibos' },
      ],
      expr: [
        { p: 'Vengo por trabajo.', n: 'Respuesta en el control.' },
        { p: 'Me voy a quedar seis meses.', n: '' },
        { p: '¿Me puede llevar a esta dirección, por favor?', n: '' },
        { p: '¿Cuánto me va a costar, más o menos?', n: '' },
        { p: 'Tengo una reserva a nombre de Rossi.', n: '' },
        { p: '¿A qué hora es el desayuno?', n: '' },
      ],
      col: [{ p: 'recoger el equipaje', n: '' }, { p: 'rellenar un formulario', n: 'No "compilar".' }, { p: 'coger un taxi', n: 'En América Latina: tomar un taxi.' }],
      scen: [{ p: 'En el control de pasaportes, responda a las preguntas; después regístrese en el hotel.', mode: 'speak', keys: ['Vengo por trabajo', 'Me voy a quedar', 'Tengo una reserva'], model: 'Buenos días. Vengo por trabajo. Empiezo en el hospital de la ciudad. Me voy a quedar seis meses. Aquí tiene mi contrato. Gracias. Hola, tengo una reserva a nombre de Rossi. ¿A qué hora es el desayuno?' }],
    },
    {
      id: 'es-abr-primera', cat: 'firstweek', title: 'La primera semana: presentarse, instrucciones, aclaraciones', l: 'B1', icon: 'user',
      intro: 'Empezar en un trabajo nuevo: presentarse, entender instrucciones y pedir aclaraciones sin vergüenza.',
      words: [
        { w: 'el compañero de trabajo', tr: 'collega', def: 'Persona que trabaja con usted.', ex: 'Mis compañeros de trabajo son muy amables.', g: 'm', pl: 'los compañeros de trabajo' },
        { w: 'el responsable', tr: 'responsabile', def: 'Persona a cargo de un equipo.', ex: 'La responsable me va a enseñar el servicio.', g: 'm', pl: 'los responsables' },
        { w: 'la tarjeta identificativa', tr: 'badge', def: 'Tarjeta con su nombre para entrar.', ex: 'Necesita la tarjeta identificativa para abrir la puerta.', g: 'f', pl: 'las tarjetas identificativas' },
        { w: 'el turno', tr: 'turno', def: 'Período de trabajo.', ex: 'Mi primer turno empieza a las ocho.', g: 'm', pl: 'los turnos' },
        { w: 'enseñar el sitio', tr: 'far vedere il posto', def: 'Mostrar el lugar de trabajo.', ex: 'Te enseño el sitio.' },
        { w: 'pillarle el truco', tr: 'prenderci la mano (colloquiale)', def: 'Aprender a hacer algo.', ex: 'Enseguida le pillarás el truco.' },
      ],
      expr: [
        { p: 'Hola, soy nuevo. Acabo de empezar en el equipo.', n: '' },
        { p: 'Perdona, ¿me lo puedes repetir más despacio?', n: 'Pedir aclaraciones es normal.' },
        { p: 'A ver si lo he entendido: primero entro en el sistema y luego imprimo la lista, ¿no?', n: 'Resumir para comprobar.' },
        { p: '¿Qué significa esa sigla?', n: '' },
        { p: '¿A quién le pregunto si tengo un problema?', n: '' },
        { p: 'Gracias, me ayuda mucho.', n: '' },
      ],
      col: [{ p: 'pedir una aclaración', n: '' }, { p: 'seguir las instrucciones', n: '' }, { p: 'empezar un trabajo', n: '' }],
      scen: [{ p: 'Su primer día: preséntese a un compañero y compruebe que ha entendido las instrucciones.', mode: 'speak', keys: ['soy nuevo', '¿me lo puedes repetir', 'A ver si lo he entendido'], model: 'Hola, soy nuevo. Me llamo Luca y acabo de empezar en el equipo. Perdona, ¿me lo puedes repetir más despacio? A ver si lo he entendido: primero entro en el sistema y luego imprimo la lista, ¿no? ¿A quién le pregunto si tengo un problema? Gracias, me ayuda mucho.' }],
    },
    {
      id: 'es-abr-piso', cat: 'daily', title: 'Alquilar un piso y hablar con el casero', l: 'B1', icon: 'clipboard',
      intro: 'Visitar un piso, preguntar por el contrato y comunicar un problema al propietario.',
      words: [
        { w: 'el casero', tr: 'padrone di casa', def: 'Persona que alquila el piso.', ex: 'Tengo que llamar al casero por la calefacción.', g: 'm', pl: 'los caseros' },
        { w: 'la fianza', tr: 'deposito cauzionale', def: 'Dinero que se paga al principio y se devuelve al final.', ex: 'La fianza es de un mes.', g: 'f', pl: 'las fianzas' },
        { w: 'los gastos', tr: 'spese, bollette', def: 'Luz, agua, gas y comunidad.', ex: '¿Los gastos están incluidos?', g: 'm', pl: '(plural)' },
        { w: 'el contrato de alquiler', tr: 'contratto d\'affitto', def: 'Documento del alquiler.', ex: 'El contrato de alquiler es de un año.', g: 'm', pl: 'los contratos de alquiler' },
        { w: 'amueblado', tr: 'arredato', def: 'Con muebles.', ex: '¿El piso está amueblado?' },
        { w: 'la avería', tr: 'guasto', def: 'Algo que no funciona.', ex: 'Hay una avería en la calefacción.', g: 'f', pl: 'las averías' },
      ],
      expr: [
        { p: '¿Los gastos están incluidos en el alquiler?', n: '' },
        { p: '¿Cuánto dura el contrato?', n: '' },
        { p: '¿Cuándo podría entrar a vivir?', n: '' },
        { p: 'Le llamo por un problema en el piso.', n: '' },
        { p: '¿Podría mandar a alguien a verlo?', n: '' },
      ],
      col: [{ p: 'pagar el alquiler', n: '' }, { p: 'firmar el contrato', n: '' }, { p: 'avisar de una avería', n: '' }],
      scen: [{ p: 'Llame al casero: la calefacción no funciona. Explique el problema y pregunte cuándo puede venir alguien.', mode: 'speak', keys: ['Le llamo por', '¿Podría mandar a alguien', 'no funciona'], model: 'Hola, soy Luca, del cuarto piso. Le llamo por un problema en el piso. La calefacción no funciona desde ayer por la tarde y hace mucho frío. ¿Podría mandar a alguien a verlo? Estoy en casa a partir de las seis.' }],
    },
    {
      id: 'es-abr-banco', cat: 'daily', title: 'Banco, documentos y trámites', l: 'B1', icon: 'briefcase',
      intro: 'Abrir una cuenta, empadronarse y saber qué documentos hacen falta.',
      words: [
        { w: 'abrir una cuenta', tr: 'aprire un conto', def: 'Empezar una cuenta en el banco.', ex: 'Quería abrir una cuenta.' },
        { w: 'el empadronamiento', tr: 'iscrizione anagrafica', def: 'Registro en el ayuntamiento del lugar donde vive.', ex: 'Para el empadronamiento necesita el contrato.', g: 'm', pl: '—' },
        { w: 'la tarjeta de débito', tr: 'carta di debito', def: 'Tarjeta que usa el dinero de su cuenta.', ex: 'La tarjeta de débito llega por correo.', g: 'f', pl: 'las tarjetas de débito' },
        { w: 'la cita previa', tr: 'appuntamento (uffici)', def: 'Cita que hay que pedir antes de ir.', ex: '¿Hace falta cita previa?', g: 'f', pl: 'las citas previas' },
        { w: 'el formulario', tr: 'modulo', def: 'Documento con preguntas.', ex: 'Rellene este formulario, por favor.', g: 'm', pl: 'los formularios' },
        { w: 'la transferencia', tr: 'bonifico', def: 'Envío de dinero entre cuentas.', ex: 'Tengo que hacer una transferencia a Italia.', g: 'f', pl: 'las transferencias' },
      ],
      expr: [
        { p: '¿Qué documentos necesito?', n: '' },
        { p: 'Acabo de llegar por trabajo.', n: '' },
        { p: '¿Cuánto tarda?', n: '' },
        { p: '¿Tiene alguna comisión?', n: '' },
        { p: '¿Me lo puede apuntar, por favor?', n: '' },
      ],
      col: [{ p: 'rellenar un formulario', n: '' }, { p: 'hacer una transferencia', n: '' }, { p: 'pedir cita previa', n: '' }],
      scen: [{ p: 'En el banco: abra una cuenta, explique su situación y pregunte qué documentos necesita.', mode: 'speak', keys: ['abrir una cuenta', '¿Qué documentos necesito', 'Acabo de llegar'], model: 'Buenos días. Quería abrir una cuenta. Acabo de llegar por trabajo. ¿Qué documentos necesito? Tengo el pasaporte y el contrato, pero todavía no tengo el empadronamiento. ¿Cuánto tarda? ¿La tarjeta tiene alguna comisión?' }],
    },
    {
      id: 'es-abr-salud', cat: 'daily', title: 'La sanidad como paciente: centro de salud, farmacia', l: 'B1', icon: 'heart',
      intro: 'Pedir cita en el centro de salud, explicar un problema y comprar medicamentos en la farmacia.',
      words: [
        { w: 'el centro de salud', tr: 'ambulatorio / medico di base', def: 'Centro de atención primaria.', ex: 'Tengo que pedir cita en el centro de salud.', g: 'm', pl: 'los centros de salud' },
        { w: 'la tarjeta sanitaria', tr: 'tessera sanitaria', def: 'Tarjeta del sistema público de salud.', ex: '¿Tiene la tarjeta sanitaria?', g: 'f', pl: 'las tarjetas sanitarias' },
        { w: 'los síntomas', tr: 'sintomi', def: 'Señales de una enfermedad.', ex: '¿Qué síntomas tiene?', g: 'm', pl: '(plural)' },
        { w: 'el farmacéutico', tr: 'farmacista', def: 'Persona que trabaja en la farmacia.', ex: 'Pregúntele al farmacéutico.', g: 'm', pl: 'los farmacéuticos' },
        { w: 'sin receta', tr: 'senza ricetta', def: 'Sin prescripción médica.', ex: 'Esto se vende sin receta.' },
        { w: 'el dolor de garganta', tr: 'mal di gola', def: 'Molestia en la garganta.', ex: 'Tengo dolor de garganta desde hace tres días.', g: 'm', pl: '—' },
      ],
      expr: [
        { p: 'Quería pedir cita con el médico de cabecera.', n: '' },
        { p: 'Tengo dolor de garganta desde hace tres días.', n: 'desde hace + tiempo.' },
        { p: '¿Me puede dar algo sin receta?', n: '' },
        { p: '¿Cada cuánto me lo tomo?', n: '' },
        { p: '¿Lo puedo tomar con mi otra medicación?', n: '' },
      ],
      col: [{ p: 'pedir cita', n: '' }, { p: 'tomar una pastilla', n: '' }, { p: 'encontrarse mejor', n: '' }],
      scen: [{ p: 'En la farmacia: describa sus síntomas y pregunte qué puede tomar y cada cuánto.', mode: 'speak', keys: ['desde hace', 'sin receta', '¿Cada cuánto'], model: 'Buenos días. Tengo dolor de garganta desde hace tres días y estoy un poco cansado. No tengo fiebre. ¿Me puede dar algo sin receta? ¿Cada cuánto me lo tomo? ¿Lo puedo tomar con mi otra medicación?' }],
    },
    {
      id: 'es-abr-diario', cat: 'daily', title: 'Compras y transporte público', l: 'A2', icon: 'map',
      intro: 'Comprar, preguntar direcciones, billetes y horarios.',
      words: [
        { w: 'el billete de ida y vuelta', tr: 'biglietto andata e ritorno', def: 'Billete para ir y volver.', ex: 'Un billete de ida y vuelta al centro, por favor.', g: 'm', pl: 'los billetes de ida y vuelta' },
        { w: 'el andén', tr: 'binario', def: 'Lugar donde se sube al tren.', ex: 'El tren sale del andén cuatro.', g: 'm', pl: 'los andenes' },
        { w: 'recargar', tr: 'ricaricare', def: 'Poner más dinero en una tarjeta.', ex: 'Tengo que recargar la tarjeta de transporte.' },
        { w: 'el pasillo', tr: 'corsia', def: 'Espacio entre estanterías.', ex: 'El arroz está en el pasillo seis.', g: 'm', pl: 'los pasillos' },
        { w: 'la devolución', tr: 'reso, rimborso', def: 'Devolver un producto y recuperar el dinero.', ex: '¿Puedo hacer una devolución?', g: 'f', pl: 'las devoluciones' },
        { w: 'hacer transbordo', tr: 'cambiare (mezzo)', def: 'Cambiar de tren o de línea.', ex: '¿Tengo que hacer transbordo?' },
      ],
      expr: [
        { p: 'Perdone, ¿qué autobús va al hospital?', n: '' },
        { p: '¿Tengo que hacer transbordo?', n: '' },
        { p: '¿Dónde está el arroz?', n: '' },
        { p: '¿Puedo pagar con tarjeta?', n: '' },
        { p: 'Quería devolver esto, por favor.', n: '' },
      ],
      col: [{ p: 'coger el autobús', n: 'En América Latina: tomar el autobús.' }, { p: 'perder el tren', n: '' }, { p: 'pagar con tarjeta', n: '' }],
      scen: [{ p: 'En la estación: compre un billete y pregunte de qué andén sale el tren y si tiene que hacer transbordo.', mode: 'speak', keys: ['ida y vuelta', '¿Tengo que hacer transbordo', 'andén'], model: 'Hola, un billete de ida y vuelta al centro, por favor. ¿Puedo pagar con tarjeta? ¿De qué andén sale? ¿Tengo que hacer transbordo? Gracias. ¿Y a qué hora sale el último tren de vuelta?' }],
    },
    {
      id: 'es-abr-trabajo', cat: 'workplace', title: 'En el trabajo: charla, reuniones, pedir ayuda', l: 'B1', icon: 'users',
      intro: 'Interacción diaria en el trabajo: charlar, dar una opinión, discrepar con educación y pedir ayuda.',
      words: [
        { w: 'la charla', tr: 'chiacchierata', def: 'Conversación ligera.', ex: 'Una charla en la pausa del café ayuda mucho.', g: 'f', pl: 'las charlas' },
        { w: 'ponerse al día', tr: 'aggiornarsi', def: 'Contarse las novedades.', ex: '¿Nos ponemos al día después de la reunión?' },
        { w: 'el punto de vista', tr: 'punto di vista', def: 'Una opinión.', ex: 'Entiendo tu punto de vista, pero…', g: 'm', pl: 'los puntos de vista' },
        { w: 'el plazo', tr: 'scadenza', def: 'Tiempo máximo para hacer algo.', ex: 'El plazo termina el viernes.', g: 'm', pl: 'los plazos' },
        { w: 'echar una mano', tr: 'dare una mano', def: 'Ayudar (coloquial).', ex: '¿Me echas una mano con esto?' },
        { w: 'ir con retraso', tr: 'essere in ritardo', def: 'Llegar o avanzar tarde.', ex: 'Perdona, voy con retraso.' },
      ],
      expr: [
        { p: '¿Qué tal el fin de semana?', n: '' },
        { p: 'En mi opinión, deberíamos empezar por los casos urgentes.', n: '' },
        { p: 'Entiendo lo que dices, pero no sé si va a funcionar.', n: 'Discrepar con educación.' },
        { p: 'Perdona, ¿me echas una mano con esto?', n: '' },
        { p: '¿Puedo añadir algo?', n: 'Interrumpir con educación.' },
      ],
      col: [{ p: 'cumplir un plazo', n: '' }, { p: 'plantear una cuestión', n: '' }, { p: 'hacer una propuesta', n: '' }],
      scen: [{ p: 'En una reunión de equipo, dé su opinión sobre el nuevo cuadrante y discrepe con educación de un compañero.', mode: 'speak', keys: ['En mi opinión', 'Entiendo lo que dices', '¿Puedo añadir algo'], model: '¿Puedo añadir algo? En mi opinión, el nuevo cuadrante es una buena idea, pero deberíamos empezar por los turnos de fin de semana. Entiendo lo que dices sobre los costes, pero no sé si va a funcionar con menos personal por la noche. Quizás podríamos probarlo un mes y luego revisarlo.' }],
    },
    {
      id: 'es-abr-social', cat: 'social', social: true, title: 'Vida social: amigos, invitaciones, planes', l: 'B1', icon: 'message',
      intro: 'Hacer amigos, aceptar y rechazar invitaciones, quedar, conversación informal y humor.',
      words: [
        { w: 'quedar', tr: 'darsi appuntamento', def: 'Acordar verse con alguien.', ex: '¿Quedamos el sábado?' },
        { w: 'apetecer', tr: 'avere voglia', def: 'Tener ganas (funciona como gustar).', ex: '¿Te apetece un café?' },
        { w: 'apuntarse', tr: 'aggregarsi', def: 'Unirse a un plan.', ex: '¡Me apunto!' },
        { w: 'tomar algo', tr: 'bere qualcosa', def: 'Ir a un bar a beber algo.', ex: '¿Vamos a tomar algo después del trabajo?' },
        { w: 'el plan', tr: 'programma, piano', def: 'Algo que se va a hacer.', ex: '¿Tienes plan para el viernes?', g: 'm', pl: 'los planes' },
        { w: 'llevar algo', tr: 'portare qualcosa', def: 'Traer algo a casa de alguien.', ex: '¿Llevo algo?' },
      ],
      expr: [
        { p: '¿Te apetece tomar algo después del trabajo?', n: '' },
        { p: 'Me encantaría, pero el sábado trabajo.', n: 'Rechazar con educación.' },
        { p: '¿Y si quedamos la semana que viene?', n: '' },
        { p: '¿Llevo algo?', n: 'Cuando le invitan a casa.' },
        { p: 'Avísame cuando te venga bien.', n: '' },
      ],
      col: [{ p: 'hacer planes', n: '' }, { p: 'rechazar una invitación', n: '' }, { p: 'pasarlo bien', n: '' }],
      scen: [{ p: 'Una compañera le invita a salir. Rechace con educación el sábado y proponga otro día.', mode: 'speak', keys: ['Me encantaría, pero', '¿Y si quedamos', 'Avísame'], model: '¡Gracias por avisarme! Me encantaría, pero el sábado trabajo. ¿Y si quedamos la semana que viene? El jueves por la tarde estoy libre. ¿Llevo algo? Avísame cuando te venga bien.' }],
    },
  ];
  LOS.lang.register({ code: 'es', abroad });
})();
