/* Français — Vivre à l'étranger : de l'arrivée à la vie sociale. */
(function () {
  'use strict';
  const LOS = window.LOS;
  const abroad = [
    {
      id: 'fr-abr-arrivee', cat: 'arrival', title: 'L\'arrivée : aéroport, contrôle, taxi, hôtel', l: 'A2', icon: 'globe',
      intro: 'Les premières heures : contrôle des passeports, taxi, enregistrement à l\'hôtel. Des phrases courtes, claires et polies.',
      words: [
        { w: 'le contrôle des passeports', tr: 'controllo passaporti', def: 'Endroit où l\'on vérifie les passeports.', ex: 'Le contrôle des passeports a été très rapide.', g: 'm', pl: 'les contrôles des passeports' },
        { w: "la carte d'embarquement", tr: 'carta d\'imbarco', def: 'Document pour monter dans l\'avion.', ex: "Votre carte d'embarquement, s'il vous plaît.", g: 'f', pl: "les cartes d'embarquement" },
        { w: 'les bagages', tr: 'bagagli', def: 'Valises et sacs de voyage.', ex: "Mes bagages ne sont pas arrivés.", g: 'm', pl: '(pluriel)' },
        { w: 'le motif du séjour', tr: 'motivo del soggiorno', def: 'Pourquoi on voyage.', ex: 'Quel est le motif de votre séjour ?', g: 'm', pl: '—' },
        { w: 'la réservation', tr: 'prenotazione', def: 'Chambre réservée.', ex: "J'ai une réservation au nom de Rossi.", g: 'f', pl: 'les réservations' },
        { w: 'le reçu', tr: 'ricevuta', def: 'Papier qui prouve un paiement.', ex: 'Je peux avoir un reçu, s\'il vous plaît ?', g: 'm', pl: 'les reçus' },
      ],
      expr: [
        { p: 'Je suis ici pour le travail.', n: 'Réponse au contrôle.' },
        { p: 'Je reste six mois.', n: '' },
        { p: "Vous pouvez m'emmener à cette adresse, s'il vous plaît ?", n: '' },
        { p: 'Ça coûte combien, à peu près ?', n: '' },
        { p: "J'ai une réservation au nom de Rossi.", n: '' },
        { p: 'Le petit-déjeuner est à quelle heure ?', n: '' },
      ],
      col: [{ p: 'récupérer ses bagages', n: '' }, { p: 'remplir un formulaire', n: 'Et non « compiler ».' }, { p: 'prendre un taxi', n: '' }],
      scen: [{ p: 'Au contrôle des passeports, répondez aux questions ; ensuite, présentez-vous à la réception de l\'hôtel.', mode: 'speak', keys: ['Je suis ici pour le travail', 'Je reste', "J'ai une réservation"], model: "Bonjour. Je suis ici pour le travail. Je commence à l'hôpital universitaire. Je reste six mois. Voici mon contrat. Merci. Bonjour, j'ai une réservation au nom de Rossi. Le petit-déjeuner est à quelle heure ?" }],
    },
    {
      id: 'fr-abr-semaine', cat: 'firstweek', title: 'La première semaine : se présenter, consignes, demander des précisions', l: 'B1', icon: 'user',
      intro: 'Commencer un nouveau poste : se présenter, comprendre les consignes et demander des précisions sans gêne.',
      words: [
        { w: "l'intégration", tr: 'inserimento', def: 'La période d\'accueil d\'un nouvel employé.', ex: "Mon intégration dure deux semaines.", g: 'f', pl: '—' },
        { w: 'la responsable', tr: 'la responsabile', def: 'La personne qui dirige l\'équipe.', ex: 'La responsable va me faire visiter le service.', g: 'f', pl: 'les responsables' },
        { w: 'le badge', tr: 'badge', def: 'Carte pour entrer dans le bâtiment.', ex: 'Il faut votre badge pour ouvrir la porte.', g: 'm', pl: 'les badges' },
        { w: 'la garde', tr: 'turno di guardia', def: 'Période de travail de nuit ou de week-end.', ex: 'Ma première garde est samedi.', g: 'f', pl: 'les gardes' },
        { w: 'faire visiter', tr: 'far fare il giro', def: 'Montrer un lieu à quelqu\'un.', ex: 'Je vous fais visiter ?' },
        { w: 'prendre le coup de main', tr: 'prenderci la mano', def: 'Apprendre à bien faire quelque chose.', ex: 'Vous allez vite prendre le coup de main.' },
      ],
      expr: [
        { p: "Bonjour, je suis nouveau. Je viens d'arriver dans l'équipe.", n: '' },
        { p: 'Pardon, vous pouvez répéter plus lentement ?', n: 'Demander des précisions est normal.' },
        { p: "Si j'ai bien compris, je me connecte d'abord, puis j'imprime la liste ?", n: 'Reformuler pour vérifier.' },
        { p: 'Ce sigle, ça veut dire quoi ?', n: '' },
        { p: "À qui je peux m'adresser si j'ai un problème ?", n: '' },
        { p: "Merci, ça m'aide beaucoup.", n: '' },
      ],
      col: [{ p: 'demander des précisions', n: '' }, { p: 'suivre les consignes', n: '' }, { p: 'prendre son poste', n: '' }],
      scen: [{ p: 'Votre premier jour : présentez-vous à une collègue et vérifiez que vous avez compris les consignes.', mode: 'speak', keys: ['je suis nouveau', 'répéter plus lentement', "Si j'ai bien compris"], model: "Bonjour, je suis nouveau. Je m'appelle Luca et je viens d'arriver dans l'équipe. Pardon, vous pouvez répéter plus lentement ? Si j'ai bien compris, je me connecte d'abord, puis j'imprime la liste ? À qui je peux m'adresser si j'ai un problème ? Merci, ça m'aide beaucoup." }],
    },
    {
      id: 'fr-abr-logement', cat: 'daily', title: 'Louer un appartement, parler au propriétaire', l: 'B1', icon: 'clipboard',
      intro: 'Visiter un appartement, poser des questions sur le bail, signaler un problème au propriétaire.',
      words: [
        { w: 'le propriétaire', tr: 'padrone di casa', def: 'La personne qui loue l\'appartement.', ex: 'Je dois appeler le propriétaire pour le chauffage.', g: 'm', pl: 'les propriétaires' },
        { w: 'la caution', tr: 'deposito cauzionale', def: 'Argent versé au début et rendu à la fin (aussi : dépôt de garantie).', ex: 'La caution est d\'un mois de loyer.', g: 'f', pl: 'les cautions' },
        { w: 'les charges', tr: 'spese condominiali / utenze', def: 'Eau, chauffage, entretien de l\'immeuble.', ex: 'Les charges sont comprises ?', g: 'f', pl: '(pluriel)' },
        { w: 'le bail', tr: 'contratto d\'affitto', def: 'Le contrat de location.', ex: 'Le bail est de trois ans.', g: 'm', pl: 'les baux' },
        { w: 'meublé', tr: 'arredato', def: 'Avec des meubles.', ex: 'L\'appartement est meublé ?' },
        { w: 'la fuite', tr: 'perdita', def: 'De l\'eau qui coule là où il ne faut pas.', ex: 'Il y a une fuite sous l\'évier.', g: 'f', pl: 'les fuites' },
      ],
      expr: [
        { p: 'Les charges sont comprises dans le loyer ?', n: '' },
        { p: 'Le bail est de combien de temps ?', n: '' },
        { p: "Je pourrais emménager à partir de quand ?", n: '' },
        { p: "Je vous appelle à cause d'un problème dans l'appartement.", n: '' },
        { p: "Vous pourriez envoyer quelqu'un ?", n: '' },
      ],
      col: [{ p: 'payer le loyer', n: '' }, { p: 'signer le bail', n: '' }, { p: 'signaler un problème', n: '' }],
      scen: [{ p: 'Appelez le propriétaire : le chauffage ne marche pas. Expliquez le problème et demandez quand quelqu\'un peut passer.', mode: 'speak', keys: ['Je vous appelle à cause', "envoyer quelqu'un", 'ne marche pas'], model: "Bonjour, c'est Luca, de l'appartement du quatrième. Je vous appelle à cause d'un problème dans l'appartement. Le chauffage ne marche pas depuis hier soir et il fait très froid. Vous pourriez envoyer quelqu'un ? Je suis chez moi à partir de six heures." }],
    },
    {
      id: 'fr-abr-banque', cat: 'daily', title: 'Banque, papiers et démarches', l: 'B1', icon: 'briefcase',
      intro: 'Ouvrir un compte, faire les démarches et savoir quels papiers sont nécessaires.',
      words: [
        { w: 'ouvrir un compte', tr: 'aprire un conto', def: 'Créer un compte bancaire.', ex: "Je voudrais ouvrir un compte." },
        { w: 'le justificatif de domicile', tr: 'prova di residenza', def: 'Document qui prouve votre adresse.', ex: 'Vous avez un justificatif de domicile ?', g: 'm', pl: 'les justificatifs de domicile' },
        { w: 'la carte bancaire', tr: 'carta bancaria', def: 'Carte liée au compte.', ex: 'La carte bancaire arrive par courrier.', g: 'f', pl: 'les cartes bancaires' },
        { w: 'le rendez-vous', tr: 'appuntamento', def: 'Heure fixée à l\'avance.', ex: 'Il faut prendre rendez-vous ?', g: 'm', pl: 'les rendez-vous' },
        { w: 'le formulaire', tr: 'modulo', def: 'Document à remplir.', ex: 'Remplissez ce formulaire, s\'il vous plaît.', g: 'm', pl: 'les formulaires' },
        { w: 'le virement', tr: 'bonifico', def: 'Transfert d\'argent entre comptes.', ex: 'Je dois faire un virement en Italie.', g: 'm', pl: 'les virements' },
      ],
      expr: [
        { p: 'Quels papiers il me faut ?', n: '' },
        { p: "Je viens d'arriver pour le travail.", n: '' },
        { p: 'Ça prend combien de temps ?', n: '' },
        { p: 'Il y a des frais ?', n: '' },
        { p: 'Vous pouvez me le noter, s\'il vous plaît ?', n: '' },
      ],
      col: [{ p: 'remplir un formulaire', n: '' }, { p: 'faire un virement', n: '' }, { p: 'prendre rendez-vous', n: '' }],
      scen: [{ p: 'À la banque : ouvrez un compte, expliquez votre situation et demandez quels papiers il faut.', mode: 'speak', keys: ['ouvrir un compte', 'Quels papiers', 'justificatif de domicile'], model: "Bonjour. Je voudrais ouvrir un compte. Je viens d'arriver pour le travail. Quels papiers il me faut ? J'ai mon passeport et mon contrat, mais je n'ai pas encore de justificatif de domicile. Ça prend combien de temps ? Il y a des frais pour la carte bancaire ?" }],
    },
    {
      id: 'fr-abr-sante', cat: 'daily', title: 'Se soigner : médecin traitant, pharmacie', l: 'B1', icon: 'heart',
      intro: 'Choisir un médecin traitant, décrire un problème, acheter un médicament à la pharmacie.',
      words: [
        { w: 'le médecin traitant', tr: 'medico di base', def: 'Médecin qui vous suit habituellement.', ex: 'Il faut déclarer un médecin traitant.', g: 'm', pl: 'les médecins traitants' },
        { w: 'la carte Vitale', tr: 'tessera sanitaria (Francia)', def: 'Carte de l\'Assurance maladie.', ex: 'Vous avez votre carte Vitale ?', g: 'f', pl: 'les cartes Vitale' },
        { w: 'les symptômes', tr: 'sintomi', def: 'Signes d\'une maladie.', ex: 'Quels sont vos symptômes ?', g: 'm', pl: '(pluriel)' },
        { w: 'le pharmacien', tr: 'farmacista', def: 'Personne qui travaille en pharmacie.', ex: 'Demandez conseil au pharmacien.', g: 'm', pl: 'les pharmaciens' },
        { w: 'sans ordonnance', tr: 'senza ricetta', def: 'Sans prescription.', ex: 'Ça se vend sans ordonnance.' },
        { w: 'le mal de gorge', tr: 'mal di gola', def: 'Douleur dans la gorge.', ex: "J'ai mal à la gorge depuis trois jours.", g: 'm', pl: '—' },
      ],
      expr: [
        { p: 'Je voudrais prendre rendez-vous avec un médecin généraliste.', n: '' },
        { p: "J'ai mal à la gorge depuis trois jours.", n: 'depuis + présent.' },
        { p: "Vous avez quelque chose sans ordonnance pour ça ?", n: '' },
        { p: 'Je dois le prendre combien de fois par jour ?', n: '' },
        { p: 'Je peux le prendre avec mes autres médicaments ?', n: '' },
      ],
      col: [{ p: 'prendre rendez-vous', n: '' }, { p: 'prendre un comprimé', n: '' }, { p: 'aller mieux', n: '' }],
      scen: [{ p: 'À la pharmacie : décrivez vos symptômes et demandez ce que vous pouvez prendre et combien de fois.', mode: 'speak', keys: ['depuis trois jours', 'sans ordonnance', 'combien de fois'], model: "Bonjour. J'ai mal à la gorge depuis trois jours et je suis un peu fatigué. Je n'ai pas de fièvre. Vous avez quelque chose sans ordonnance pour ça ? Je dois le prendre combien de fois par jour ? Je peux le prendre avec mes autres médicaments ?" }],
    },
    {
      id: 'fr-abr-quotidien', cat: 'daily', title: 'Courses et transports en commun', l: 'A2', icon: 'map',
      intro: 'Faire les courses, demander son chemin, billets et horaires.',
      words: [
        { w: "l'aller-retour", tr: 'andata e ritorno', def: 'Billet pour aller et revenir.', ex: 'Un aller-retour pour le centre-ville, s\'il vous plaît.', g: 'm', pl: 'les allers-retours' },
        { w: 'la voie', tr: 'binario', def: 'Endroit où l\'on prend le train.', ex: 'Le train part de la voie quatre.', g: 'f', pl: 'les voies' },
        { w: 'recharger', tr: 'ricaricare', def: 'Remettre de l\'argent sur une carte.', ex: 'Je dois recharger ma carte de transport.' },
        { w: 'le rayon', tr: 'reparto (negozio)', def: 'Partie d\'un magasin.', ex: 'Le riz est au rayon épicerie.', g: 'm', pl: 'les rayons' },
        { w: 'le remboursement', tr: 'rimborso', def: 'Argent rendu.', ex: 'Je peux avoir un remboursement ?', g: 'm', pl: 'les remboursements' },
        { w: 'la correspondance', tr: 'coincidenza', def: 'Changement de train ou de ligne.', ex: "Il y a une correspondance à Lyon.", g: 'f', pl: 'les correspondances' },
      ],
      expr: [
        { p: "Pardon, quel bus va à l'hôpital ?", n: '' },
        { p: 'Il faut changer ?', n: '' },
        { p: 'Où est-ce que je trouve le riz ?', n: '' },
        { p: 'Je peux payer par carte ?', n: '' },
        { p: 'Je voudrais rendre cet article, s\'il vous plaît.', n: '' },
      ],
      col: [{ p: 'prendre le bus', n: '' }, { p: 'rater le train', n: '' }, { p: 'payer par carte', n: '' }],
      scen: [{ p: 'À la gare : achetez un billet et demandez de quelle voie part le train et s\'il faut changer.', mode: 'speak', keys: ['aller-retour', 'Il faut changer', 'voie'], model: "Bonjour, un aller-retour pour le centre-ville, s'il vous plaît. Je peux payer par carte ? Le train part de quelle voie ? Il faut changer ? Merci. Et le dernier train pour revenir, c'est à quelle heure ?" }],
    },
    {
      id: 'fr-abr-travail', cat: 'workplace', title: 'Au travail : discuter, réunions, demander de l\'aide', l: 'B1', icon: 'users',
      intro: 'Les échanges de tous les jours au travail : discuter, donner son avis, être en désaccord poliment, demander de l\'aide.',
      words: [
        { w: 'la pause café', tr: 'pausa caffè', def: 'Moment de pause pour discuter.', ex: 'On en parle à la pause café ?', g: 'f', pl: 'les pauses café' },
        { w: 'faire le point', tr: 'fare il punto', def: 'Faire un bilan rapide.', ex: 'On fait le point après la réunion ?' },
        { w: 'le point de vue', tr: 'punto di vista', def: 'Une opinion.', ex: 'Je comprends ton point de vue, mais…', g: 'm', pl: 'les points de vue' },
        { w: 'le délai', tr: 'scadenza, tempo', def: 'Temps accordé pour faire quelque chose.', ex: 'Le délai est très court.', g: 'm', pl: 'les délais' },
        { w: 'donner un coup de main', tr: 'dare una mano', def: 'Aider (familier).', ex: 'Tu peux me donner un coup de main ?' },
        { w: 'être en retard', tr: 'essere in ritardo', def: 'Arriver après l\'heure.', ex: 'Désolé, je suis en retard.' },
      ],
      expr: [
        { p: "Ça s'est bien passé, ton week-end ?", n: '' },
        { p: 'À mon avis, on devrait commencer par les cas urgents.', n: '' },
        { p: "Je vois ce que tu veux dire, mais je ne suis pas sûr que ça marche.", n: 'Désaccord poli.' },
        { p: 'Tu peux me donner un coup de main ?', n: '' },
        { p: "Je peux ajouter quelque chose ?", n: 'Interrompre poliment.' },
      ],
      col: [{ p: 'respecter un délai', n: '' }, { p: 'soulever une question', n: '' }, { p: 'faire une proposition', n: '' }],
      scen: [{ p: 'En réunion d\'équipe, donnez votre avis sur le nouveau planning et exprimez poliment votre désaccord avec un collègue.', mode: 'speak', keys: ['À mon avis', 'Je vois ce que tu veux dire', 'Je peux ajouter quelque chose'], model: "Je peux ajouter quelque chose ? À mon avis, le nouveau planning est une bonne idée, mais on devrait commencer par les gardes du week-end. Je vois ce que tu veux dire sur les coûts, mais je ne suis pas sûr que ça marche avec moins de personnel la nuit. On pourrait peut-être l'essayer un mois et en reparler ensuite." }],
    },
    {
      id: 'fr-abr-social', cat: 'social', social: true, title: 'Vie sociale : amis, invitations, projets', l: 'B1', icon: 'message',
      intro: 'Se faire des amis, accepter ou refuser une invitation, fixer un rendez-vous, conversation familière.',
      words: [
        { w: 'ça te dit', tr: 'ti va', def: 'Pour proposer quelque chose (familier).', ex: 'Ça te dit, un café ?' },
        { w: 'boire un verre', tr: 'bere qualcosa', def: 'Aller dans un bar.', ex: 'On va boire un verre après le travail ?' },
        { w: 'se voir', tr: 'vedersi', def: 'Se rencontrer.', ex: 'On se voit samedi ?' },
        { w: 'décliner une invitation', tr: 'declinare un invito', def: 'Dire non poliment.', ex: 'Je dois malheureusement décliner l\'invitation.' },
        { w: 'apporter quelque chose', tr: 'portare qualcosa', def: 'Venir avec quelque chose.', ex: "J'apporte quelque chose ?" },
        { w: 'arranger', tr: 'andare bene (a qualcuno)', def: 'Convenir à quelqu\'un.', ex: 'Jeudi, ça t\'arrange ?' },
      ],
      expr: [
        { p: 'Ça te dit de boire un verre après le travail ?', n: '' },
        { p: "J'aimerais bien, mais samedi je travaille.", n: 'Refuser poliment.' },
        { p: 'Et la semaine prochaine, plutôt ?', n: '' },
        { p: "J'apporte quelque chose ?", n: 'Quand on est invité chez quelqu\'un.' },
        { p: "Dis-moi quand ça t'arrange.", n: '' },
      ],
      col: [{ p: 'faire des projets', n: '' }, { p: 'accepter une invitation', n: '' }, { p: 'bien s\'amuser', n: '' }],
      scen: [{ p: 'Une collègue vous invite. Refusez poliment pour samedi et proposez un autre jour.', mode: 'speak', keys: ["J'aimerais bien, mais", 'la semaine prochaine', "Dis-moi quand"], model: "Merci pour l'invitation ! J'aimerais bien, mais samedi je travaille. Et la semaine prochaine, plutôt ? Jeudi soir, je suis libre. J'apporte quelque chose ? Dis-moi quand ça t'arrange." }],
    },
  ];
  LOS.lang.register({ code: 'fr', abroad });
})();
