/* French language pack — grammar curriculum A1 → C2 (français standard de France, avec notes Belgique / Suisse / Québec).
 * French-specific by design: gender & articles (incl. partitive), agreement (adjectives, past participle),
 * the pronoun system (COD/COI, y, en, double pronouns), conjugation and the subjunctive are first-class topics.
 * `ecat` links each topic to a French error category (gender, agreement, conjugation, pronouns, prepositions, subjunctive…). */
(function () {
  'use strict';
  const LOS = window.LOS;
  const gap = (q, a, d, w, x) => Object.assign({ t: 'gap', q, a: [].concat(a), d, w }, x);
  const mc = (q, o, a, d, w, x) => Object.assign({ t: 'mc', q, o, a, d, w }, x);
  const fix = (q, a, d, w, x) => Object.assign({ t: 'fix', q, a: [].concat(a), d, w }, x);
  const tr = (q, s, a, d, w, x) => Object.assign({ t: 'tr', q, s, a: [].concat(a), d, w }, x);
  const M = { m: 1 };

  const grammar = [
    /* ---------------- A1 ---------------- */
    { id: 'fr-etre-avoir', l: 'A1', cat: 'Verbes', ecat: 'conjugation', title: 'Être et avoir', sum: 'Je suis / j\'ai — les deux verbes de base (et des auxiliaires).',
      explain: ['être : je suis, tu es, il/elle est, nous sommes, vous êtes, ils/elles sont.', 'avoir : j\'ai, tu as, il a, nous avons, vous avez, ils ont. Élision : je → j\' devant voyelle.', 'Comme en italien : j\'ai 35 ans, j\'ai faim, j\'ai froid. Mais : il y a = c\'è / ci sono.'],
      ex: ['Je suis anesthésiste.', 'Nous avons une réunion à huit heures.', 'Vous êtes Madame Martin ?'],
      use: 'Présente-toi : nom, profession, âge, famille — avec être et avoir.',
      x: [gap('Je ___ médecin.', 'suis', 1, 'je → suis.'), gap('Tu ___ quel âge ?', 'as', 1, 'L\'âge avec avoir.'),
        mc('Nous ___ fatigués.', ['avons', 'sommes', 'êtes'], 1, 1, 'nous → sommes.'), fix('Je ai trente ans.', ["J'ai trente ans."], 1, 'Élision : j\'ai.'),
        gap('Le patient ___ de la fièvre.', 'a', 1, 'il → a.', M)] },
    { id: 'fr-present-er', l: 'A1', cat: 'Verbes', ecat: 'conjugation', title: 'Présent : verbes en -er', sum: '-e, -es, -e, -ons, -ez, -ent (muet !).',
      explain: ['parler : je parle, tu parles, il parle, nous parlons, vous parlez, ils parlent.', 'Les terminaisons -e, -es, -e, -ent se prononcent de la même façon : [paʁl].', 'Particularités : manger → nous mangeons ; commencer → nous commençons ; appeler → j\'appelle ; acheter → j\'achète.'],
      ex: ['Je travaille à l\'hôpital.', 'Vous parlez italien ?', 'Nous commençons à sept heures.'],
      use: 'Décris ta journée avec cinq verbes en -er.',
      x: [gap('Nous ___ (travailler) ensemble.', 'travaillons', 1, 'nous → -ons.'), gap('Ils ___ (parler) français.', 'parlent', 1, 'ils → -ent (muet).'),
        gap('Nous ___ (commencer) à huit heures.', 'commençons', 2, 'ç devant o.'), fix('Vous parlé italien ?', ['Vous parlez italien ?'], 2, 'vous → -ez.'),
        gap('Je m\'___ (appeler) Luca.', 'appelle', 2, 'appeler → j\'appelle (deux l).')] },
    { id: 'fr-present-irreg', l: 'A1', cat: 'Verbes', ecat: 'conjugation', title: 'Présent : verbes irréguliers fréquents', sum: 'aller, faire, venir, prendre, pouvoir, vouloir, devoir.',
      explain: ['aller : vais, vas, va, allons, allez, vont. faire : fais, fais, fait, faisons, faites, font.', 'venir : viens, viens, vient, venons, venez, viennent. prendre : prends, prends, prend, prenons, prenez, prennent.', 'pouvoir : peux, peux, peut, pouvons, pouvez, peuvent. vouloir : veux… veulent. devoir : dois… doivent.'],
      ex: ['Je vais au bloc.', 'Vous pouvez respirer profondément ?', 'Qu\'est-ce que vous faites dans la vie ?'],
      use: 'Écris cinq phrases sur ta semaine avec des verbes irréguliers.',
      x: [gap('Je ___ (aller) à l\'hôpital.', 'vais', 1, 'aller → je vais.'), gap('Vous ___ (faire) du sport ?', 'faites', 2, 'faire → vous faites (pas "faisez").'),
        gap('Ils ___ (prendre) le métro.', 'prennent', 2, 'prendre → ils prennent.'), fix('Vous pouvé respirer ?', ['Vous pouvez respirer ?'], 1, 'pouvoir → vous pouvez.', M),
        gap('Nous ___ (devoir) partir.', 'devons', 2, 'devoir → nous devons.')] },
    { id: 'fr-articles-genre', l: 'A1', cat: 'Noms', ecat: 'gender', title: 'Articles et genre', sum: 'le/la/l\'/les, un/une/des — et les genres différents de l\'italien.',
      explain: ['Défini : le (m), la (f), l\' (devant voyelle/h muet), les (pl.). Indéfini : un, une, des.', 'Repères : -tion, -sion, -té, -ure, -ence → féminin ; -ment, -age, -isme, -eau → masculin.', 'Pièges pour italophones : la douleur (il dolore), la fleur, la dent, la couleur, l\'erreur (f), la valeur — mais le lait, le problème, le système, le groupe.'],
      ex: ['La douleur est forte.', 'J\'ai un problème.', 'L\'analyse est normale.'],
      use: 'Écris dix noms de ton lieu de travail avec leur article.',
      x: [mc('___ douleur est très forte.', ['Le', 'La', 'L\''], 1, 1, 'la douleur (≠ il dolore).', M), mc('J\'ai fait ___ erreur.', ['un', 'une'], 1, 2, 'une erreur (f).'),
        gap('___ hôpital est grand. (défini)', "L'", 1, 'h muet → l\'.', M), fix('Le couleur est jolie.', ['La couleur est jolie.'], 2, 'la couleur (f).'),
        mc('___ problème est réglé.', ['Le', 'La'], 0, 1, 'le problème (m).'), mc('Il a mal à ___ dent.', ['le', 'la'], 1, 2, 'la dent (f).', M)] },
    { id: 'fr-pluriel', l: 'A1', cat: 'Noms', ecat: 'agreement', title: 'Le pluriel', sum: '-s (muet), -x, -aux : un hôpital → des hôpitaux.',
      explain: ['Règle générale : + -s, qu\'on n\'entend pas : un patient → des patients.', '-al → -aux : un hôpital → des hôpitaux ; -eau/-eu → -x : un bureau → des bureaux.', 'Irréguliers : un œil → des yeux ; -s/-x/-z ne changent pas : un bras → des bras. On entend le pluriel surtout dans l\'article : le/les.'],
      ex: ['des hôpitaux', 'les yeux', 'deux infirmiers'],
      use: 'Mets au pluriel dix noms du domaine médical.',
      x: [gap('un hôpital → deux ___', 'hôpitaux', 1, '-al → -aux.', M), gap('un œil → les ___', 'yeux', 2, 'Irrégulier.', M),
        gap('un bureau → des ___', 'bureaux', 1, '-eau → -x.'), fix('Les animals sont malades.', ['Les animaux sont malades.'], 2, '-al → -aux.')] },
    { id: 'fr-negation', l: 'A1', cat: 'Négation', ecat: 'grammar', title: 'La négation', sum: 'ne … pas, ne … plus, ne … jamais, ne … rien ; pas de + nom.',
      explain: ['ne + verbe + pas : Je ne fume pas. Devant voyelle : n\' : Je n\'ai pas faim.', 'Autres : ne … plus (non più), ne … jamais (mai), ne … rien (niente), ne … personne (nessuno).', 'Après une négation, un/une/des/du/de la → de/d\' : J\'ai une voiture → Je n\'ai pas de voiture. À l\'oral, le "ne" tombe souvent : J\'sais pas.'],
      ex: ['Je n\'ai pas d\'allergies.', 'Il ne mange plus.', 'Je ne bois jamais d\'alcool.'],
      use: 'Écris cinq choses que tu ne fais jamais ou plus.',
      x: [tr('Je fume. (négation)', 'Je', ['Je ne fume pas.'], 1, 'ne … pas.'), fix('Je n\'ai pas des allergies.', ["Je n'ai pas d'allergies."], 2, 'pas de/d\' après la négation.', M),
        mc('Il ___ mange ___ depuis hier. (non più)', ['ne … pas', 'ne … plus', 'ne … jamais'], 1, 1, 'ne … plus.', M), fix('Je ne ai pas faim.', ["Je n'ai pas faim."], 1, 'Élision : n\'.'),
        gap('Il n\'y a ___ dans la salle. (nessuno)', 'personne', 2, 'ne … personne.')] },
    { id: 'fr-questions', l: 'A1', cat: 'Phrase', ecat: 'grammar', title: 'Poser des questions', sum: 'Intonation, est-ce que, inversion ; qui, que, où, quand, comment, pourquoi, combien.',
      explain: ['Trois registres : Vous avez mal ? (familier/courant) — Est-ce que vous avez mal ? (courant) — Avez-vous mal ? (soutenu).', 'Inversion avec -t- entre deux voyelles : A-t-il de la fièvre ?', 'Qu\'est-ce que (cosa), qui (chi), où (dove), quand, comment, pourquoi, combien (de), quel/quelle (+ nom, accord !).'],
      ex: ['Où avez-vous mal ?', 'Depuis quand avez-vous de la fièvre ?', 'Est-ce que vous prenez des médicaments ?'],
      use: 'Écris dix questions pour un premier entretien avec un patient.',
      x: [gap('___ avez-vous mal ? — Au ventre.', 'Où', 1, 'Lieu → où.', M), tr('Vous prenez des médicaments ? (est-ce que)', 'Est-ce que', ['Est-ce que vous prenez des médicaments ?'], 1, 'est-ce que + ordre normal.', M),
        mc('___ âge avez-vous ?', ['Quel', 'Quelle', 'Qu\'est-ce que'], 0, 2, 'l\'âge (m) → quel.'), fix('A il de la fièvre ?', ['A-t-il de la fièvre ?'], 2, 'Inversion : a-t-il (t euphonique).', M),
        gap('___ est-ce que vous faites ce soir ?', "Qu'", 2, 'Qu\'est-ce que = cosa.')] },
    { id: 'fr-adjectifs', l: 'A1', cat: 'Adjectifs', ecat: 'agreement', title: 'Les adjectifs : accord et place', sum: 'un patient fatigué / une patiente fatiguée ; un grand hôpital.',
      explain: ['Accord en genre et nombre : grand/grande/grands/grandes ; -eux → -euse ; -if → -ive ; -el → -elle.', 'Place : en général après le nom (une douleur aiguë), mais avant pour beauté, âge, bonté, taille (BAGS) : un petit problème, une nouvelle collègue.', 'Formes devant voyelle : un bel hôpital, un nouvel appareil, un vieil homme.'],
      ex: ['Une douleur aiguë.', 'Une nouvelle collègue.', 'Des résultats inquiétants.'],
      use: 'Décris ton service avec dix adjectifs bien accordés.',
      x: [gap('La patiente est très ___. (fatigué)', 'fatiguée', 1, 'Féminin → -e.', M), gap('Une douleur ___. (aigu)', 'aiguë', 2, 'aigu → aiguë.', M),
        mc('C\'est un ___ hôpital.', ['beau', 'bel', 'belle'], 1, 2, 'Devant voyelle : bel.'), fix('Une collègue nouvelle est arrivée.', ['Une nouvelle collègue est arrivée.'], 2, '"nouveau" se place avant le nom.'),
        gap('Les résultats sont ___. (sérieux, pluriel)', 'sérieux', 2, '-eux invariable au masc. pl.')] },
    { id: 'fr-possessifs', l: 'A1', cat: 'Déterminants', ecat: 'agreement', title: 'Possessifs et démonstratifs', sum: 'mon/ma/mes, son/sa/ses ; ce/cet/cette/ces.',
      explain: ['Le possessif s\'accorde avec l\'objet possédé, pas avec le possesseur : son mari / sa femme (de lui ou d\'elle !).', 'Devant voyelle, mon/ton/son même au féminin : mon amie, son ordonnance.', 'Démonstratifs : ce (m), cet (m devant voyelle), cette (f), ces (pl.) : cet examen, cette semaine.'],
      ex: ['Votre carte Vitale, s\'il vous plaît.', 'Sa fille l\'accompagne.', 'Cet examen dure dix minutes.'],
      use: 'Décris ta famille avec des possessifs.',
      x: [mc('Madame Dubois et ___ mari', ['son', 'sa', 'ses'], 0, 2, 'le mari (m) → son (même si le possesseur est une femme).'), gap('___ examen dure dix minutes. (démonstratif)', 'Cet', 2, 'Devant voyelle : cet.', M),
        mc('C\'est ___ amie Claire.', ['ma', 'mon'], 1, 2, 'Devant voyelle : mon amie.'), gap('Vous avez ___ ordonnance ? (vous)', 'votre', 1, 'vous → votre.', M)] },
    { id: 'fr-prepositions-base', l: 'A1', cat: 'Prépositions', ecat: 'prepositions', title: 'Prépositions et articles contractés', sum: 'à + le = au, de + le = du ; à Paris, en France, au Canada, chez le médecin.',
      explain: ['à + le = au, à + les = aux ; de + le = du, de + les = des. (à la, à l\', de la, de l\' ne changent pas.)', 'Villes : à Paris. Pays féminins : en France, en Italie ; masculins : au Canada, au Japon ; pluriels : aux États-Unis.', 'Chez + personne : chez le médecin, chez moi. Aller à l\'hôpital, au bloc, aux urgences.'],
      ex: ['Je vais aux urgences.', 'J\'habite en Italie, à Milan.', 'Il revient du bloc.'],
      use: 'Décris où tu vas pendant une semaine normale.',
      x: [gap('Je vais ___ urgences.', 'aux', 1, 'à + les = aux.', M), gap('Il revient ___ bloc opératoire.', 'du', 1, 'de + le = du.', M),
        mc('J\'habite ___ Italie.', ['à', 'en', 'au'], 1, 1, 'Pays féminin → en.'), fix('Je vais à le médecin.', ['Je vais chez le médecin.'], 2, 'Personne → chez.'),
        mc('Elle travaille ___ Canada.', ['en', 'au', 'à'], 1, 2, 'Pays masculin → au.')] },

    /* ---------------- A2 ---------------- */
    { id: 'fr-partitif', l: 'A2', cat: 'Articles', ecat: 'gender', title: 'L\'article partitif', sum: 'du pain, de la fièvre, de l\'eau, des vertiges — une quantité non précisée.',
      explain: ['du (m), de la (f), de l\' (voyelle), des (pl.) : Vous avez de la fièvre ? Je bois de l\'eau.', 'L\'italien dit souvent "ho febbre" sans article — le français en exige un : j\'ai de la fièvre.', 'Après une quantité ou une négation → de : beaucoup de patients, un peu de sel, pas de fièvre.'],
      ex: ['Vous avez de la fièvre ?', 'Il faut boire de l\'eau.', 'Il n\'a pas de douleur.'],
      use: 'Décris ce que tu manges et bois dans une journée.',
      x: [gap('Vous avez ___ fièvre ?', 'de la', 1, 'la fièvre → de la.', M), gap('Il faut boire ___ eau.', "de l'", 1, 'Voyelle → de l\'.'),
        fix('J\'ai fièvre depuis hier.', ["J'ai de la fièvre depuis hier."], 2, 'Partitif obligatoire (≠ italien "ho febbre").', M), mc('Il y a beaucoup ___ patients.', ['des', 'de', 'du'], 1, 2, 'Après une quantité → de.', M),
        fix('Je ne prends pas du sucre.', ['Je ne prends pas de sucre.'], 2, 'Négation → de.')] },
    { id: 'fr-cod-coi', l: 'A2', cat: 'Pronoms', ecat: 'pronouns', title: 'Pronoms COD et COI', sum: 'le/la/les (direct) et lui/leur (indirect) — placés avant le verbe.',
      explain: ['COD (qui ? quoi ?) : le, la, l\', les. COI (à qui ?) : lui, leur. Je, tu, nous, vous : me, te, nous, vous pour les deux.', 'Place : avant le verbe conjugué : Je le vois. Je lui explique. Avec un infinitif : avant l\'infinitif : Je vais l\'appeler.', 'Verbes + à (COI) : parler à, téléphoner à, expliquer à, demander à, répondre à. Mais : aider qqn, appeler qqn (COD) — ≠ italien "gli telefono".'],
      ex: ['Je l\'appelle demain.', 'Je lui ai expliqué la procédure.', 'Vous pouvez les prendre avec de l\'eau.'],
      use: 'Réponds à cinq questions en remplaçant les noms par des pronoms.',
      x: [gap('Tu vois le docteur ? — Oui, je ___ vois.', 'le', 1, 'COD masculin.'), gap('J\'ai parlé au patient. → Je ___ ai parlé.', 'lui', 2, 'parler à → lui.', M),
        mc('Les comprimés, vous pouvez ___ prendre avec de l\'eau.', ['les', 'leur', 'lui'], 0, 2, 'COD pluriel → les.', M), fix('Je lui appelle demain. (le médecin)', ["Je l'appelle demain."], 3, 'appeler qqn → COD (≠ italien "gli telefono").'),
        tr('Je téléphone à mes parents.', 'Je', ['Je leur téléphone.'], 2, 'téléphoner à + pluriel → leur.')] },
    { id: 'fr-passe-compose', l: 'A2', cat: 'Temps', ecat: 'tense', title: 'Le passé composé', sum: 'avoir/être + participe passé ; accord avec être.',
      explain: ['La plupart des verbes : avoir + participe : j\'ai mangé, j\'ai fini, j\'ai pris, j\'ai fait, j\'ai vu.', 'Être avec les verbes de mouvement/changement (aller, venir, arriver, partir, entrer, sortir, naître, mourir, rester, tomber…) et tous les pronominaux : accord avec le sujet : elle est arrivée.', 'Participes irréguliers : pris, fait, dit, écrit, mis, vu, eu, été, ouvert, mort, né.'],
      ex: ['J\'ai bien dormi.', 'La patiente est tombée hier soir.', 'Nous avons opéré à neuf heures.'],
      use: 'Raconte ce que tu as fait hier (huit phrases).',
      x: [gap('Hier, j\'___ travaillé tard.', 'ai', 1, 'travailler → avoir.'), gap('Elle est ___ (arriver) à huit heures.', 'arrivée', 2, 'être → accord : arrivée.'),
        gap('Qu\'est-ce qui s\'est ___ ? (passer)', 'passé', 2, 'se passer → être.', M), fix('J\'ai prendu le métro.', ['J\'ai pris le métro.'], 2, 'prendre → pris.'),
        mc('La patiente ___ tombée dans le couloir.', ['a', 'est'], 1, 1, 'tomber → être.', M), fix('Nous sommes opéré le patient.', ['Nous avons opéré le patient.'], 2, 'opérer qqn → avoir.', M)] },
    { id: 'fr-imparfait', l: 'A2', cat: 'Temps', ecat: 'tense', title: 'L\'imparfait', sum: 'Descriptions, habitudes et contexte au passé.',
      explain: ['Radical de "nous" au présent + -ais, -ais, -ait, -ions, -iez, -aient : nous parlons → je parlais.', 'Seul irrégulier : être → j\'étais.', 'Usage : description (Il était pâle), habitude (Je travaillais la nuit), action en cours (Je dormais quand…).'],
      ex: ['Quand j\'étais étudiant, je travaillais le week-end.', 'Le patient était pâle et transpirait.'],
      use: 'Décris ta vie quand tu étais étudiant(e).',
      x: [gap('Quand j\'___ (être) enfant, j\'habitais à Naples.', 'étais', 1, 'être → étais.'), gap('Le patient ___ (avoir) de la fièvre.', 'avait', 1, 'Description → imparfait.', M),
        gap('Nous ___ (finir) tard tous les jours.', 'finissions', 2, 'nous finissons → finissions.'), fix('Avant, je travaille la nuit.', ['Avant, je travaillais la nuit.'], 2, 'Habitude passée → imparfait.')] },
    { id: 'fr-pc-imparfait', l: 'A2', cat: 'Temps', ecat: 'tense', title: 'Passé composé ou imparfait ?', sum: 'Décor (imparfait) ↔ événement (passé composé).', pre: ['fr-passe-compose', 'fr-imparfait'],
      explain: ['Imparfait = arrière-plan, description, habitude, action en cours.', 'Passé composé = événement ponctuel, action terminée qui fait avancer le récit.', 'Je dormais (décor) quand le téléphone a sonné (événement).'],
      ex: ['J\'étais de garde quand il est arrivé.', 'Il faisait nuit et il pleuvait.'],
      use: 'Raconte une garde difficile en combinant les deux temps.',
      x: [mc('Je ___ quand le téléphone a sonné.', ['ai dormi', 'dormais'], 1, 1, 'Action en cours interrompue.'), mc('Hier, je ___ chez le médecin parce que j\'avais mal à la gorge.', ['suis allé', 'allais'], 0, 2, 'Événement ponctuel.', M),
        gap('Quand je suis arrivé, le patient ___ (être) déjà réveillé.', 'était', 2, 'Description → imparfait.', M), mc('Enfant, j\'___ peur des chiens.', ['ai eu', 'avais'], 1, 2, 'État prolongé → imparfait.')] },
    { id: 'fr-futur', l: 'A2', cat: 'Temps', ecat: 'tense', title: 'Futur proche, futur simple, passé récent', sum: 'Je vais partir / je partirai / je viens de partir.',
      explain: ['Futur proche : aller + infinitif (très courant à l\'oral) : On va vous endormir.', 'Futur simple : infinitif + -ai, -as, -a, -ons, -ez, -ont. Irréguliers : serai, aurai, irai, ferai, pourrai, viendrai, devrai, verrai, saurai.', 'Passé récent : venir de + infinitif : Il vient de se réveiller.'],
      ex: ['On va vous faire une prise de sang.', 'Vous vous sentirez mieux demain.', 'Le patient vient de se réveiller.'],
      use: 'Explique à un patient ce qui va se passer demain.',
      x: [gap('Nous ___ vous endormir. (futur proche)', 'allons', 1, 'aller + infinitif.', M), gap('Demain, vous ___ (être) mieux.', 'serez', 2, 'être → ser-.', M),
        gap('Il ___ de se réveiller (à l\'instant).', 'vient', 1, 'venir de.', M), fix('Je poverai venir demain.', ['Je pourrai venir demain.'], 2, 'pouvoir → pourr-.')] },
    { id: 'fr-comparaison', l: 'A2', cat: 'Adjectifs', ecat: 'grammar', title: 'Comparatif et superlatif', sum: 'plus/moins/aussi … que ; meilleur / mieux ; le plus…',
      explain: ['plus/moins/aussi + adjectif + que : plus grand que.', 'bon → meilleur (adjectif) ; bien → mieux (adverbe) : Ce traitement est meilleur. Je vais mieux. Jamais "plus bon".', 'Superlatif : le/la/les plus … (de) : le meilleur service de la ville.'],
      ex: ['Je me sens mieux qu\'hier.', 'C\'est la meilleure solution.'],
      use: 'Compare deux hôpitaux ou deux villes.',
      x: [mc('Aujourd\'hui, je vais ___ qu\'hier.', ['meilleur', 'mieux', 'plus bien'], 1, 1, 'Adverbe → mieux.', M), fix('C\'est plus bon.', ["C'est meilleur."], 1, 'bon → meilleur.'),
        gap('Elle est aussi compétente ___ lui.', 'que', 1, 'aussi … que.'), gap('C\'est la ___ solution. (bon)', 'meilleure', 2, 'meilleur + accord.')] },
    { id: 'fr-pronominaux', l: 'A2', cat: 'Verbes', ecat: 'conjugation', title: 'Les verbes pronominaux', sum: 'se lever, s\'appeler, se sentir — et le passé composé avec être.',
      explain: ['me, te, se, nous, vous, se : je me lève, vous vous sentez.', 'Passé composé avec être + accord : Elle s\'est levée. Nous nous sommes réveillés.', 'Fréquents en contexte médical : se sentir, se reposer, s\'allonger, se déshabiller, se blesser, se casser (le bras).'],
      ex: ['Comment vous sentez-vous ?', 'Allongez-vous, s\'il vous plaît.', 'Elle s\'est cassé le poignet.'],
      use: 'Décris ta matinée avec cinq verbes pronominaux.',
      x: [gap('Comment vous ___ sentez-vous ?', 'vous', 1, 'vous → vous.', M), gap('Je ___ lève à six heures.', 'me', 1, 'je → me.'),
        gap('Elle s\'est ___ (lever) tôt.', 'levée', 2, 'Accord avec le sujet.'), fix('Je suis senti mal.', ['Je me suis senti mal.'], 2, 'Le pronom réfléchi est obligatoire.', M)] },
    { id: 'fr-imperatif', l: 'A2', cat: 'Verbes', ecat: 'pronouns', title: 'L\'impératif (avec pronoms)', sum: 'Respirez ! Asseyez-vous. Ne vous levez pas.',
      explain: ['vous : respirez, toussez, ouvrez la bouche ; tu : respire, ouvre (pas de -s pour les verbes en -er).', 'Affirmatif : pronom après, avec trait d\'union : Asseyez-vous. Allongez-vous. Dites-moi.', 'Négatif : pronom avant : Ne vous levez pas. Ne le prenez pas à jeun.'],
      ex: ['Respirez profondément… soufflez.', 'Allongez-vous sur le dos.', 'Ne mangez rien après minuit.'],
      use: 'Donne des instructions pour un examen clinique.',
      x: [tr('Vous vous asseyez.', 'Asseyez', ['Asseyez-vous.'], 1, 'Impératif + pronom après.', M), tr('Vous ne vous levez pas.', 'Ne', ['Ne vous levez pas.'], 2, 'Négatif : pronom avant.', M),
        gap('___-moi où vous avez mal. (dire, vous)', 'Dites', 2, 'dire → dites.', M), fix('Respires profondément ! (tu)', ['Respire profondément !'], 2, 'tu, verbe en -er : pas de -s.')] },
    { id: 'fr-temps-prep', l: 'A2', cat: 'Prépositions', ecat: 'prepositions', title: 'Depuis, il y a, pendant, dans', sum: 'depuis (da), il y a (fa), pendant (per), dans (fra).',
      explain: ['depuis + durée/date = l\'action continue : J\'habite ici depuis trois ans.', 'il y a + durée = fa : Je suis arrivé il y a deux jours. pendant = durata chiusa : J\'ai travaillé pendant dix ans à Rome.', 'dans + durée = fra (futur) : Le médecin arrive dans dix minutes. en + durée = il tempo impiegato : Je l\'ai fait en une heure.'],
      ex: ['Depuis quand avez-vous mal ?', 'Il a été opéré il y a deux jours.', 'Les résultats arrivent dans une heure.'],
      use: 'Décris ton parcours professionnel avec ces quatre prépositions.',
      x: [mc('J\'habite à Lyon ___ trois ans.', ['il y a', 'depuis', 'pendant'], 1, 1, 'Continue → depuis.'), mc('Il a été opéré ___ deux jours.', ['il y a', 'depuis', 'dans'], 0, 2, 'fa → il y a.', M),
        mc('Le chirurgien arrive ___ dix minutes.', ['en', 'dans', 'depuis'], 1, 2, 'fra (futuro) → dans.', M), fix('J\'ai travaillé à Rome depuis dix ans, puis je suis parti.', ["J'ai travaillé à Rome pendant dix ans, puis je suis parti."], 3, 'Durée terminée → pendant.')] },

    /* ---------------- B1 ---------------- */
    { id: 'fr-relatifs', l: 'B1', cat: 'Phrase', ecat: 'pronouns', title: 'Les pronoms relatifs : qui, que, où, dont', sum: 'qui (sujet), que (COD), où (lieu/temps), dont (de + …).',
      explain: ['qui = sujet : le médecin qui m\'a opéré. que/qu\' = COD : le médecin que j\'ai vu.', 'où = lieu ET temps : l\'hôpital où je travaille, le jour où il est arrivé.', 'dont remplace de + … : le patient dont je t\'ai parlé (parler de), le traitement dont nous avons besoin (avoir besoin de).'],
      ex: ['C\'est la patiente dont je vous ai parlé.', 'Le service où je travaille est neuf.'],
      use: 'Définis cinq objets de l\'hôpital avec des relatives.',
      x: [gap('Le médecin ___ m\'a opéré est très gentil.', 'qui', 1, 'Sujet → qui.', M), gap('Le patient ___ j\'ai vu hier est sorti.', 'que', 1, 'COD → que.', M),
        gap('C\'est le traitement ___ nous avons besoin.', 'dont', 2, 'avoir besoin de → dont.', M), mc('Le jour ___ il est arrivé, il pleuvait.', ['que', 'où', 'quand'], 1, 2, 'Temps → où.'),
        fix('La patiente que je t\'ai parlé est sortie.', ["La patiente dont je t'ai parlé est sortie."], 3, 'parler de → dont.', M)] },
    { id: 'fr-y-en', l: 'B1', cat: 'Pronoms', ecat: 'pronouns', title: 'Les pronoms y et en', sum: 'y = à + chose / lieu ; en = de + chose / quantité.', pre: ['fr-cod-coi'],
      explain: ['y remplace un lieu ou à + chose : Je vais à l\'hôpital → J\'y vais. Je pense à mon examen → J\'y pense.', 'en remplace de + chose, un partitif ou une quantité : Vous avez des allergies ? — Oui, j\'en ai deux. Il en parle souvent.', 'Pour les personnes : à lui / d\'elle : Je pense à lui. Je parle d\'elle.'],
      ex: ['Des comprimés ? Prenez-en deux par jour.', 'Vous allez au bloc ? — J\'y vais.', 'Vous fumez des cigarettes ? — J\'en fume dix par jour.'],
      use: 'Réponds à dix questions en utilisant y ou en.',
      x: [gap('Vous avez des enfants ? — Oui, j\'___ ai deux.', 'en', 1, 'Quantité → en.'), gap('Tu vas à Lyon ? — Oui, j\'___ vais demain.', 'y', 1, 'Lieu → y.'),
        mc('Vous fumez ? — Oui, j\'___ fume dix par jour.', ['y', 'en', 'les'], 1, 2, 'Quantité → en.', M), mc('Je pense souvent à mon examen. → J\'___ pense souvent.', ['y', 'en', 'lui'], 0, 2, 'penser à + chose → y.'),
        tr('Prenez deux comprimés. (en)', 'Prenez', ['Prenez-en deux.'], 3, 'Impératif + en.', M)] },
    { id: 'fr-doubles-pronoms', l: 'B1', cat: 'Pronoms', ecat: 'pronouns', title: 'Les doubles pronoms', sum: 'Je vous l\'envoie. Je le lui donne. Donnez-le-moi.', pre: ['fr-cod-coi', 'fr-y-en'],
      explain: ['Ordre : me/te/se/nous/vous → le/la/les → lui/leur → y → en : Je vous l\'envoie. Je le lui donne. Il y en a.', 'Impératif affirmatif : verbe-le-moi / -le-lui : Donnez-le-moi. Envoyez-les-leur.', 'Différent de l\'italien (glielo) : "le lui", pas "lui le".'],
      ex: ['Le compte rendu ? Je vous l\'envoie ce soir.', 'Il y en a encore ?', 'Donnez-le-moi, s\'il vous plaît.'],
      use: 'Réponds à cinq questions avec deux pronoms.',
      x: [gap('Tu as donné le dossier au chef ? — Oui, je ___ ai donné.', "le lui", 2, 'le + lui.'), fix('Je lui le donne.', ['Je le lui donne.'], 2, 'Ordre : le lui (≠ italien glielo).'),
        gap('Le compte rendu ? Je ___ envoie ce soir. (à vous)', "vous l'", 2, 'vous + le → vous l\'.', M), tr('Donnez le stylo à moi.', 'Donnez', ['Donnez-le-moi.'], 3, 'Impératif : -le-moi.')] },
    { id: 'fr-conditionnel', l: 'B1', cat: 'Modes', ecat: 'conjugation', title: 'Le conditionnel présent', sum: 'Politesse, conseil, souhait, hypothèse.',
      explain: ['Radical du futur + terminaisons de l\'imparfait : je voudrais, vous pourriez, il faudrait, ce serait.', 'Politesse : Pourriez-vous… ? Je voudrais… Conseil : À votre place, j\'arrêterais de fumer. Vous devriez…', 'Hypothèse : Ce serait une bonne idée.'],
      ex: ['Pourriez-vous répéter, s\'il vous plaît ?', 'À votre place, je me reposerais.', 'Il faudrait refaire une prise de sang.'],
      use: 'Écris cinq demandes polies à des collègues.',
      x: [gap('___-vous répéter, s\'il vous plaît ? (pouvoir)', 'Pourriez', 1, 'Politesse → conditionnel.'), gap('Je ___ (vouloir) un rendez-vous.', 'voudrais', 1, 'vouloir → voudr-.'),
        mc('À votre place, j\'___ de fumer.', ['arrête', 'arrêterais', 'arrêterai'], 1, 2, 'Conseil → conditionnel.', M), gap('Vous ___ (devoir) boire plus d\'eau.', 'devriez', 2, 'Conseil : vous devriez.', M)] },
    { id: 'fr-si', l: 'B1', cat: 'Modes', ecat: 'tense', title: 'Les phrases avec si', sum: 'Si + présent → futur ; si + imparfait → conditionnel.', pre: ['fr-conditionnel'],
      explain: ['Réel : Si la douleur augmente, appelez-nous / vous nous appellerez.', 'Hypothétique : Si j\'avais le temps, je ferais plus de sport.', 'Jamais de futur ni de conditionnel après si (hypothèse) : Si j\'aurais → ✗. (Interférence de l\'italien populaire "se avrei".)'],
      ex: ['Si vous avez de la fièvre, revenez aux urgences.', 'Si j\'étais vous, je demanderais un deuxième avis.'],
      use: 'Écris trois phrases réelles et trois hypothétiques.',
      x: [fix('Si j\'aurais le temps, je viendrais.', ["Si j'avais le temps, je viendrais."], 1, 'Si + imparfait.'), gap('Si la douleur ___ (augmenter), appelez-nous.', 'augmente', 1, 'Réel : si + présent.', M),
        mc('Si j\'___ vous, je demanderais un deuxième avis.', ['serais', 'étais', 'suis'], 1, 2, 'Si + imparfait.'), gap('S\'il pleut, nous ___ (rester) à la maison.', 'resterons', 2, 'Si + présent → futur.')] },
    { id: 'fr-subjonctif', l: 'B1', cat: 'Modes', ecat: 'subjunctive', title: 'Le subjonctif présent : nécessité et volonté', sum: 'Il faut que vous soyez à jeun. Je veux que tu viennes.',
      explain: ['Formation : radical de "ils" au présent + -e, -es, -e, -ions, -iez, -ent : ils prennent → que je prenne.', 'Irréguliers : être (sois, soit, soyons, soyez), avoir (aie, ait, ayez), aller (aille), faire (fasse), pouvoir (puisse), savoir (sache), vouloir (veuille).', 'Après : il faut que, il est important que, vouloir que, souhaiter que, pour que, avant que, bien que. (Sujets différents ; sinon infinitif.)'],
      ex: ['Il faut que vous soyez à jeun.', 'Je voudrais que vous preniez ce médicament.', 'Il est important que vous fassiez de l\'exercice.'],
      use: 'Écris cinq recommandations pour un patient avec "il faut que".',
      x: [gap('Il faut que vous ___ (être) à jeun.', 'soyez', 1, 'être → soyez.', M), gap('Je veux que tu ___ (venir) avec moi.', 'viennes', 2, 'venir → que tu viennes.'),
        gap('Il est important que vous ___ (faire) de l\'exercice.', 'fassiez', 2, 'faire → fassiez.', M), fix('Il faut que vous prenez ce médicament.', ['Il faut que vous preniez ce médicament.'], 2, 'il faut que + subjonctif.', M),
        mc('Je voudrais ___ cette semaine.', ['que je parte', 'partir'], 1, 2, 'Même sujet → infinitif.')] },
    { id: 'fr-pqp-indirect', l: 'B1', cat: 'Discours', ecat: 'tense', title: 'Plus-que-parfait et discours indirect', sum: 'Il a dit qu\'il avait mal ; elle m\'a demandé si…', pre: ['fr-pc-imparfait'],
      explain: ['Plus-que-parfait : avoir/être à l\'imparfait + participe : j\'avais pris, elle était partie — antériorité dans le passé.', 'Discours indirect au passé : présent → imparfait ; passé composé → plus-que-parfait ; futur → conditionnel.', 'Questions : Il m\'a demandé si… / ce que… / où… ; ordres : Il m\'a dit de m\'asseoir.'],
      ex: ['Le patient a dit qu\'il avait pris ses médicaments.', 'Elle m\'a demandé si l\'opération serait longue.'],
      use: 'Résume une conversation récente au discours indirect.',
      x: [tr('"J\'ai mal", a dit le patient.', 'Le patient a dit qu\'il', ['Le patient a dit qu\'il avait mal.'], 1, 'présent → imparfait.', M), tr('"J\'ai pris mes médicaments", a dit-elle.', 'Elle a dit qu\'elle', ["Elle a dit qu'elle avait pris ses médicaments."], 2, 'PC → plus-que-parfait.', M),
        gap('Il m\'a demandé ___ je pouvais rester.', 'si', 1, 'Question oui/non → si.'), tr('"Je viendrai demain", a dit le chirurgien.', 'Le chirurgien a dit qu\'il', ["Le chirurgien a dit qu'il viendrait demain.", "Le chirurgien a dit qu'il viendrait le lendemain."], 2, 'futur → conditionnel.')] },
    { id: 'fr-connecteurs', l: 'B1', cat: 'Discours', ecat: 'grammar', title: 'Connecteurs : parce que, car, puisque, donc, pourtant, alors que', sum: 'Cause, conséquence, opposition.',
      explain: ['Cause : parce que (réponse à pourquoi), car (écrit, après la principale), puisque (cause connue), comme (en tête de phrase).', 'Conséquence : donc, alors, c\'est pourquoi, si bien que. Opposition : mais, pourtant, cependant, alors que, tandis que.', 'Attention : "pourtant" ≠ italien "pertanto" (= donc) !'],
      ex: ['L\'étude est petite ; pourtant, les résultats sont intéressants.', 'Comme il n\'y avait pas de lit, nous avons reporté l\'opération.'],
      use: 'Écris un paragraphe argumentatif avec quatre connecteurs.',
      x: [mc('L\'étude est petite ; ___, les résultats sont intéressants.', ['donc', 'pourtant', 'car'], 1, 1, 'Opposition → pourtant.'), mc('"Pourtant" signifie…', ['pertanto', 'eppure / tuttavia', 'perché'], 1, 2, 'Faux ami !'),
        mc('___ il n\'y avait pas de lit, nous avons reporté l\'opération.', ['Comme', 'Car', 'Donc'], 0, 2, 'Cause en tête → comme.', M), gap('Il était fatigué, ___ il est rentré. (conséquence)', ['donc', 'alors'], 1, 'Conséquence.')] },

    /* ---------------- B2 ---------------- */
    { id: 'fr-subj-emotion', l: 'B2', cat: 'Modes', ecat: 'subjunctive', title: 'Subjonctif : émotion, doute, opinion négative', sum: 'Je suis content que… ; je doute que… ; je ne pense pas que…', pre: ['fr-subjonctif'],
      explain: ['Émotion + que + subjonctif : Je suis heureux que vous alliez mieux. Je regrette que…', 'Doute / possibilité : Je doute que, il est possible que, il se peut que + subjonctif.', 'Penser/croire que + indicatif ; ne pas penser que / penser que ? (interrogation) + subjonctif. Espérer que + indicatif !'],
      ex: ['Je ne pense pas que ce soit une bonne idée.', 'J\'espère que vous allez mieux.', 'Il est possible que les résultats soient faussés.'],
      use: 'Donne ton avis sur une proposition avec je pense que / je ne pense pas que.',
      x: [gap('Je suis content que vous ___ (aller) mieux.', 'alliez', 1, 'Émotion → subjonctif.', M), gap('Je ne pense pas que ce ___ (être) une bonne idée.', 'soit', 1, 'Opinion négative → subjonctif.'),
        mc('J\'espère que vous ___ bien.', ['allez', 'alliez'], 0, 2, 'espérer que + indicatif.'), fix('Je doute que le traitement est efficace.', ['Je doute que le traitement soit efficace.'], 2, 'Doute → subjonctif.', M),
        mc('Je pense qu\'il ___ raison.', ['a', 'ait'], 0, 2, 'penser que (affirmatif) + indicatif.')] },
    { id: 'fr-conjonctions', l: 'B2', cat: 'Modes', ecat: 'subjunctive', title: 'Conjonctions + subjonctif / indicatif', sum: 'bien que, pour que, avant que, à condition que + subj. ; après que + indic.', pre: ['fr-subjonctif'],
      explain: ['+ subjonctif : bien que, quoique, pour que, afin que, avant que, sans que, à condition que, à moins que, jusqu\'à ce que.', '+ indicatif : parce que, pendant que, alors que, après que (!), dès que, depuis que.', 'Même sujet → préposition + infinitif : avant de partir, pour comprendre, sans le savoir.'],
      ex: ['Bien que l\'étude soit petite, elle est rigoureuse.', 'Je vous l\'explique pour que vous compreniez.', 'Avant de partir, vérifiez la liste.'],
      use: 'Écris des instructions pour un collègue avec avant que, pour que et dès que.',
      x: [gap('Bien que l\'étude ___ (être) petite, elle est rigoureuse.', 'soit', 1, 'bien que + subjonctif.'), gap('Je vous l\'explique pour que vous ___ (comprendre).', 'compreniez', 2, 'pour que + subjonctif.', M),
        mc('Après qu\'il ___ parti, nous avons fermé.', ['soit', 'est', 'était'], 2, 3, 'après que + indicatif (ici plus-que-parfait).'), fix('Avant que je pars, je vérifie la liste.', ['Avant de partir, je vérifie la liste.'], 2, 'Même sujet → avant de + infinitif.'),
        gap('Vous pouvez sortir demain, à condition que la fièvre ___ (baisser).', 'baisse', 2, 'à condition que + subjonctif.', M)] },
    { id: 'fr-futur-ant-cond-passe', l: 'B2', cat: 'Temps', ecat: 'tense', title: 'Futur antérieur et conditionnel passé', sum: 'Quand vous aurez fini… ; J\'aurais dû… ; Si j\'avais su, je serais venu.', pre: ['fr-si'],
      explain: ['Futur antérieur : avoir/être au futur + participe : Quand vous aurez terminé le traitement, nous referons un bilan. (≠ italien "quando avrai finito" — même logique !)', 'Conditionnel passé : avoir/être au conditionnel + participe : j\'aurais dû, nous aurions pu.', 'Irréel du passé : Si + plus-que-parfait, conditionnel passé : Si nous l\'avions su, nous aurions agi plus tôt.'],
      ex: ['Quand les résultats seront arrivés, je vous appellerai.', 'Nous aurions dû intervenir plus tôt.', 'Si j\'avais su, je serais venu.'],
      use: 'Réfléchis à une décision passée avec le conditionnel passé.',
      x: [gap('Quand vous ___ (finir) le traitement, nous referons un bilan.', 'aurez fini', 2, 'Futur antérieur.', M), gap('Nous ___ (devoir) intervenir plus tôt.', 'aurions dû', 2, 'Regret → conditionnel passé.', M),
        fix('Si j\'aurais su, je serais venu.', ["Si j'avais su, je serais venu."], 1, 'Si + plus-que-parfait.'), gap('Si nous l\'avions su, nous ___ (agir) autrement.', 'aurions agi', 2, 'Irréel du passé.')] },
    { id: 'fr-passif', l: 'B2', cat: 'Voix', ecat: 'agreement', title: 'Le passif et ses alternatives', sum: 'Le patient a été opéré par… ; on l\'a opéré ; ça se soigne bien.',
      explain: ['être (au temps voulu) + participe accordé : La patiente sera opérée demain. Le patient a été transféré.', 'Agent : par (action) / de (sentiment, état) : opéré par le Dr Martin ; apprécié de tous.', 'Alternatives très fréquentes : "on" (On vous appellera) et le pronominal passif (Ce médicament se prend à jeun).'],
      ex: ['Le patient a été extubé à 10 heures.', 'Ce médicament se prend au cours du repas.', 'On vous appellera dès que possible.'],
      use: 'Décris une procédure de ton service au passif.',
      x: [gap('La patiente ___ opérée demain. (futur)', 'sera', 1, 'être au futur.', M), gap('Les patients ont été ___ (transférer) en réanimation.', 'transférés', 2, 'Accord du participe.', M),
        tr('On a opéré la patiente à 9 heures.', 'La patiente', ['La patiente a été opérée à 9 heures.'], 2, 'Passif + accord.', M), mc('"Ce comprimé se prend à jeun" signifie :', ['Le comprimé prend quelque chose.', 'On doit prendre ce comprimé à jeun.', 'Le comprimé est pris par erreur.'], 1, 2, 'Pronominal passif.', M)] },
    { id: 'fr-negation-avancee', l: 'B2', cat: 'Négation', ecat: 'grammar', title: 'Négation avancée et restriction', sum: 'ne … que, ne … ni … ni, aucun, nulle part, sans + infinitif.', pre: ['fr-negation'],
      explain: ['ne … que = seulement : Il ne prend que du paracétamol. (Ce n\'est pas une négation !)', 'ne … ni … ni : Il n\'a ni fièvre ni douleur. ne … aucun(e) : Aucun effet secondaire n\'a été observé.', 'Infinitif : ne pas + infinitif : Il est conseillé de ne pas conduire. Sans + infinitif : sans manger.'],
      ex: ['Le patient n\'a ni fièvre ni toux.', 'Il ne reste qu\'un lit.', 'Merci de ne pas fumer.'],
      use: 'Écris un compte rendu bref en utilisant quatre formes de négation.',
      x: [tr('Le patient n\'a pas de fièvre et pas de toux. (ni … ni)', 'Le patient n\'a', ["Le patient n'a ni fièvre ni toux."], 2, 'ne … ni … ni (sans article).', M), mc('"Il ne prend que du paracétamol" signifie :', ['Il ne prend pas de paracétamol.', 'Il prend seulement du paracétamol.', 'Il prend beaucoup de paracétamol.'], 1, 2, 'ne … que = seulement.', M),
        fix('Il est conseillé de ne conduire pas.', ['Il est conseillé de ne pas conduire.'], 2, 'Infinitif : ne pas + infinitif.', M), gap('___ effet secondaire n\'a été observé.', 'Aucun', 2, 'ne … aucun.', M)] },
    { id: 'fr-accord-pp', l: 'B2', cat: 'Accord', ecat: 'agreement', title: 'Accord du participe passé avec avoir', sum: 'La lettre que j\'ai écrite ; je les ai vus.', pre: ['fr-passe-compose', 'fr-cod-coi'],
      explain: ['Avec avoir, le participe s\'accorde avec le COD seulement s\'il est placé AVANT le verbe.', 'Cas typiques : pronom COD (Je les ai vus), relatif que (Les analyses que j\'ai demandées), question (Quelles mesures avez-vous prises ?).', 'Pas d\'accord avec en : Des patients, j\'en ai vu beaucoup.'],
      ex: ['Les analyses que j\'ai demandées sont arrivées.', 'Vos ordonnances ? Je les ai imprimées.'],
      use: 'Écris cinq phrases où le COD précède le verbe.',
      x: [gap('Les analyses que j\'ai ___ (demander) sont arrivées.', 'demandées', 2, 'COD "que" (les analyses, f. pl.) avant.', M), gap('Les patientes ? Je les ai ___ (voir) ce matin.', 'vues', 2, 'COD "les" (f. pl.) avant.', M),
        mc('J\'ai ___ les résultats.', ['vu', 'vus'], 0, 2, 'COD après → pas d\'accord.'), fix('La lettre que j\'ai écrit est partie.', ["La lettre que j'ai écrite est partie."], 3, 'COD "que" (la lettre) avant → écrite.')] },
    { id: 'fr-mise-en-relief', l: 'B2', cat: 'Discours', ecat: 'grammar', title: 'La mise en relief', sum: 'C\'est lui qui… ; Ce qui me préoccupe, c\'est…',
      explain: ['C\'est … qui / c\'est … que : C\'est le Dr Martin qui a opéré. C\'est demain que nous déciderons.', 'Ce qui … c\'est / ce que … c\'est : Ce qui m\'inquiète, c\'est la tension.', 'Dislocation (oral) : Ce patient, je le connais bien. Moi, je pense que…'],
      ex: ['Ce qui m\'inquiète, c\'est l\'hémodynamique.', 'C\'est lui qui a fait l\'erreur.'],
      use: 'Réponds à une critique en utilisant la mise en relief.',
      x: [tr('Le Dr Martin a opéré.', "C'est", ["C'est le Dr Martin qui a opéré."], 1, 'c\'est … qui.', M), tr('L\'hémodynamique m\'inquiète.', 'Ce qui', ["Ce qui m'inquiète, c'est l'hémodynamique."], 2, 'ce qui … c\'est.', M),
        mc('C\'est demain ___ nous déciderons.', ['qui', 'que', 'où'], 1, 2, 'Complément mis en relief → que.')] },
    { id: 'fr-registre-formel', l: 'B2', cat: 'Registre', ecat: 'register', title: 'Le registre formel à l\'écrit', sum: 'Vouvoiement, formules de lettre, "je vous prie de…".',
      explain: ['Vous de politesse avec les patients, les supérieurs et les inconnus. Le tutoiement entre collègues est fréquent en France, mais attendez qu\'on vous le propose.', 'Formules : Madame, Monsieur, / Je me permets de vous écrire au sujet de… / Je vous prie d\'agréer, Madame, Monsieur, l\'expression de mes salutations distinguées.', 'Courriel professionnel plus simple : Bonjour Madame Dubois, … Bien cordialement.'],
      ex: ['Je me permets de vous contacter au sujet de…', 'Je vous remercie par avance de votre réponse.', 'Bien cordialement,'],
      use: 'Écris un courriel formel et un courriel cordial au même destinataire.',
      x: [mc('Formule de fin dans une lettre très formelle :', ['Bisous', 'Je vous prie d\'agréer l\'expression de mes salutations distinguées.', 'À plus !'], 1, 1, 'Formule soutenue.'), mc('Début d\'un courriel professionnel courant :', ['Salut Marie,', 'Bonjour Madame Dubois,', 'Coucou,'], 1, 1, 'Bonjour + titre + nom.'),
        fix('Je me permets de te contacter, Monsieur le Directeur.', ['Je me permets de vous contacter, Monsieur le Directeur.'], 2, 'Vouvoiement.'), gap('Je vous remercie ___ avance de votre réponse.', 'par', 2, 'par avance.')] },

    /* ---------------- C1 ---------------- */
    { id: 'fr-subj-avance', l: 'C1', cat: 'Modes', ecat: 'subjunctive', title: 'Subjonctif avancé', sum: 'Relatives (quelqu\'un qui sache), superlatif + subj., subjonctif passé.', pre: ['fr-subj-emotion', 'fr-relatifs'],
      explain: ['Relative à antécédent hypothétique : Je cherche un infirmier qui sache parler allemand (existe-t-il ?). Mais : J\'ai un collègue qui sait…', 'Après un superlatif ou seul/unique/premier : C\'est le meilleur chirurgien que je connaisse.', 'Subjonctif passé (antériorité) : Je suis content que vous soyez venu. Bien qu\'il ait pris son traitement, la tension reste élevée.'],
      ex: ['Nous cherchons un médecin qui puisse commencer en mai.', 'C\'est le seul traitement qui soit validé.', 'Je regrette qu\'il soit parti si tôt.'],
      use: 'Décris le collègue idéal avec des relatives au subjonctif.',
      x: [gap('Nous cherchons un médecin qui ___ (pouvoir) commencer en mai.', 'puisse', 2, 'Antécédent hypothétique → subjonctif.'), gap('C\'est le meilleur chirurgien que je ___ (connaître).', 'connaisse', 2, 'Superlatif → subjonctif.', M),
        gap('Bien qu\'il ___ pris son traitement, la tension reste élevée. (avoir)', 'ait', 2, 'Subjonctif passé.', M), mc('J\'ai un collègue qui ___ très bien l\'allemand.', ['sache', 'sait'], 1, 2, 'Antécédent réel → indicatif.')] },
    { id: 'fr-conditionnel-nuance', l: 'C1', cat: 'Modes', ecat: 'conjugation', title: 'Le conditionnel de prudence', sum: 'Selon le patient, il aurait chuté ; le traitement serait efficace chez…', pre: ['fr-futur-ant-cond-passe'],
      explain: ['Information non vérifiée (presse, rapports, anamnèse) : Le patient aurait chuté dans la nuit. Selon l\'étude, le risque serait réduit.', 'Atténuation dans la discussion scientifique : Il semblerait que… On pourrait envisager…', 'Distance polie : Je dirais plutôt que… Il conviendrait de…'],
      ex: ['D\'après la famille, il aurait arrêté son traitement il y a une semaine.', 'Il semblerait que les résultats soient plus nuancés.'],
      use: 'Rédige une anamnèse rapportée par la famille au conditionnel.',
      x: [mc('Information non confirmée : "Le patient ___ dans la nuit."', ['a chuté', 'aurait chuté', 'chutera'], 1, 2, 'Conditionnel journalistique.', M), gap('Selon l\'étude, le risque ___ (être) réduit de moitié.', 'serait', 2, 'Prudence → conditionnel.', M),
        mc('Formule prudente :', ['C\'est faux.', 'Il conviendrait de nuancer cette conclusion.', 'Vous avez tort.'], 1, 1, 'Distance polie.')] },
    { id: 'fr-nominalisation', l: 'C1', cat: 'Style', ecat: 'grammar', title: 'La nominalisation', sum: 'Après l\'arrivée du patient… ; en cas d\'aggravation…',
      explain: ['Verbe → nom : arriver → l\'arrivée ; aggraver → l\'aggravation ; décider → la décision ; sortir → la sortie.', 'Subordonnée → groupe nominal : Si l\'état s\'aggrave → En cas d\'aggravation. Après que le patient est arrivé → Après l\'arrivée du patient.', 'Typique des comptes rendus, des titres et de l\'écrit administratif.'],
      ex: ['En cas d\'aggravation, contacter le médecin de garde.', 'Après réception des résultats, …'],
      use: 'Transforme cinq subordonnées en groupes nominaux.',
      x: [tr('Si l\'état s\'aggrave, … (en cas de)', 'En cas', ["En cas d'aggravation de l'état", "En cas d'aggravation"], 2, 'Nominalisation.', M), tr('Après que le patient est arrivé, …', 'Après', ["Après l'arrivée du patient"], 2, 'après + nom.', M),
        gap('décider → la ___', 'décision', 1, 'Nom.'), gap('sortir (de l\'hôpital) → la ___', 'sortie', 1, 'Nom.', M)] },
    { id: 'fr-connecteurs-avances', l: 'C1', cat: 'Discours', ecat: 'grammar', title: 'Connecteurs avancés', sum: 'or, en effet, néanmoins, toutefois, d\'autant plus que, dans la mesure où, quand bien même.', pre: ['fr-connecteurs'],
      explain: ['or (ma, invece — introduit un élément décisif dans un raisonnement), en effet (infatti — justifie), néanmoins / toutefois (tuttavia).', 'd\'autant plus que (tanto più che), dans la mesure où (nella misura in cui), étant donné que, compte tenu de.', 'quand bien même + conditionnel (anche se) : Quand bien même il accepterait, ce serait trop tard.'],
      ex: ['Le traitement est efficace ; toutefois, il est coûteux.', 'Il faut agir vite, d\'autant plus que le patient est âgé.'],
      use: 'Écris un paragraphe argumentatif avec cinq connecteurs avancés.',
      x: [mc('L\'opération était prévue ; ___, le patient avait de la fièvre.', ['or', 'donc', 'car'], 0, 2, 'or = élément nouveau décisif.', M), mc('Il faut agir vite, ___ le patient est âgé.', ['d\'autant plus que', 'bien que', 'pour que'], 0, 2, 'd\'autant plus que.', M),
        gap('Quand bien même il ___ (accepter), ce serait trop tard.', 'accepterait', 3, 'quand bien même + conditionnel.'), mc('"En effet" signifie…', ['in effetti / infatti', 'tuttavia', 'quindi'], 0, 1, 'Justification.')] },
    { id: 'fr-participe-present', l: 'C1', cat: 'Style', ecat: 'agreement', title: 'Participe présent, gérondif et adjectif verbal', sum: 'en marchant ; ayant terminé… ; fatiguant / fatigant.',
      explain: ['Gérondif (en + -ant) = simultanéité/manière, même sujet : On réduit le risque en mobilisant tôt.', 'Participe présent (invariable) / participe composé : Ayant terminé l\'examen, le médecin a appelé la famille.', 'Adjectif verbal (accordé, orthographe parfois différente) : un travail fatigant (fatiguant = participe), des résultats convaincants (convainquant = participe), différent/différant, précédent/précédant.'],
      ex: ['On réduit le risque en mobilisant tôt.', 'Ayant reçu les résultats, nous avons modifié le traitement.', 'Une garde fatigante.'],
      use: 'Écris cinq phrases avec le gérondif et deux avec un participe composé.',
      x: [gap('On réduit le risque ___ mobilisant tôt.', 'en', 1, 'Gérondif : en + -ant.', M), tr('Après avoir reçu les résultats, nous avons modifié le traitement.', 'Ayant', ['Ayant reçu les résultats, nous avons modifié le traitement.'], 2, 'Participe composé.', M),
        mc('Une garde très ___.', ['fatiguante', 'fatigante'], 1, 3, 'Adjectif verbal : fatigant(e).'), mc('Des arguments ___.', ['convainquants', 'convaincants'], 1, 3, 'Adjectif verbal : convaincant.')] },
    { id: 'fr-academique', l: 'C1', cat: 'Style', ecat: 'register', title: 'Le français académique et scientifique', sum: 'nous d\'auteur, il convient de, force est de constater, les résultats suggèrent…',
      explain: ['"Nous" d\'auteur (ou "on") plutôt que "je" : Nous avons inclus… Les résultats suggèrent que…', 'Formules : il convient de, il importe de, force est de constater que, il ressort de cette étude que, à cet égard.', 'Prudence : semble, pourrait, suggère, il est vraisemblable que (+ indicatif), il n\'est pas exclu que (+ subjonctif).'],
      ex: ['Force est de constater que les données manquent.', 'Il ressort de cette étude que la mobilisation précoce réduit les complications.'],
      use: 'Rédige la conclusion d\'un résumé scientifique.',
      x: [mc('Formule académique pour "on voit bien que" :', ['Force est de constater que', 'C\'est clair que', 'Évidemment'], 0, 2, 'Registre soutenu.'), gap('Il ___ de rappeler que l\'étude est monocentrique. (convenir)', 'convient', 2, 'il convient de.', M),
        mc('Il n\'est pas exclu que les résultats ___ biaisés.', ['sont', 'soient', 'seront'], 1, 3, 'il n\'est pas exclu que + subjonctif.', M)] },

    /* ---------------- C2 ---------------- */
    { id: 'fr-litteraire', l: 'C2', cat: 'Style', ecat: 'conjugation', title: 'Formes littéraires (reconnaissance) et ne explétif', sum: 'passé simple, imparfait du subjonctif ; avant qu\'il ne parte.',
      explain: ['Passé simple (écrit littéraire, presse, histoire) : il fut, il eut, il fit, ils prirent, elle naquit — à reconnaître, rarement à produire.', 'Imparfait du subjonctif (très soutenu) : qu\'il fût, qu\'il eût — dans les textes anciens.', 'Ne explétif (sans valeur négative, soutenu) : avant qu\'il ne parte, à moins qu\'il ne refuse, je crains qu\'il ne soit trop tard.'],
      ex: ['Il naquit à Lyon en 1820 et fit ses études à Paris.', 'Je crains qu\'il ne soit trop tard.'],
      use: 'Repère les passés simples dans un article d\'histoire de la médecine.',
      x: [mc('"Il fit" est le passé simple de…', ['finir', 'faire', 'falloir'], 1, 1, 'faire → il fit.'), mc('"Je crains qu\'il ne soit trop tard" signifie :', ['J\'ai peur qu\'il soit trop tard.', 'J\'ai peur qu\'il ne soit pas trop tard.'], 0, 2, 'Ne explétif : pas de négation.'),
        mc('"Elle naquit" signifie…', ['elle nagea', 'elle est née', 'elle nia'], 1, 2, 'naître → naquit.')] },
    { id: 'fr-idiomes', l: 'C2', cat: 'Idiomatique', ecat: 'naturalness', title: 'Expressions idiomatiques', sum: 'avoir le cafard, poser un lapin, tomber dans les pommes, ne pas être dans son assiette…',
      explain: ['Les idiomes donnent de la nuance mais sont souvent familiers : à manier selon le contexte.', 'Exemples : tomber dans les pommes (s\'évanouir), ne pas être dans son assiette (ne pas se sentir bien), avoir un chat dans la gorge, poser un lapin à qqn (ne pas venir), coûter les yeux de la tête, avoir du pain sur la planche.', 'Ne pas traduire mot à mot : "in bocca al lupo" → Bon courage ! / Merde ! (théâtre).'],
      ex: ['Il est tombé dans les pommes en voyant l\'aiguille.', 'Je ne suis pas dans mon assiette aujourd\'hui.'],
      use: 'Utilise trois idiomes dans un petit dialogue informel.',
      x: [mc('"Tomber dans les pommes" signifie…', ['s\'évanouir', 'cueillir des fruits', 'se tromper'], 0, 1, 's\'évanouir.', M), mc('"Ne pas être dans son assiette" signifie…', ['ne pas avoir faim', 'ne pas se sentir bien', 'être en retard'], 1, 2, 'Malaise léger.', M),
        mc('"Avoir du pain sur la planche" signifie…', ['avoir beaucoup de travail', 'être riche', 'avoir faim'], 0, 2, 'Beaucoup à faire.'), mc('Pour "in bocca al lupo" on dit :', ['Dans la bouche du loup !', 'Bon courage ! / Bonne chance !', 'Bon appétit !'], 1, 2, 'Pas de traduction littérale.')] },
    { id: 'fr-variation', l: 'C2', cat: 'Registre', ecat: 'register', title: 'Registres et variation francophone', sum: 'familier / courant / soutenu ; Belgique, Suisse, Québec.',
      explain: ['bagnole / voiture / automobile ; bosser / travailler / œuvrer ; flic / policier / agent des forces de l\'ordre. Verlan : ouf (fou), relou (lourd).', 'Belgique et Suisse : septante (70), nonante (90) ; Suisse : huitante (80). Repas : déjeuner (matin), dîner (midi), souper (soir) en Belgique, Suisse et au Québec.', 'Québec : courriel (= e-mail, adopté aussi en France), magasiner (faire du shopping), char (voiture, familier), "tu" plus fréquent.'],
      ex: ['On a bossé toute la nuit. (familier) / Nous avons travaillé toute la nuit. (courant)'],
      use: 'Écris la même information pour un ami, un patient et un rapport.',
      x: [mc('En Belgique, 70 se dit…', ['soixante-dix', 'septante', 'huitante'], 1, 1, 'septante.'), mc('Registre soutenu de "bosser" :', ['travailler', 'œuvrer', 'turbiner'], 1, 2, 'œuvrer.'),
        mc('Au Québec, "magasiner" signifie…', ['faire du shopping', 'stocker', 'travailler en magasin'], 0, 2, 'faire des courses / du shopping.'), mc('En Suisse romande, le repas de midi s\'appelle souvent…', ['le déjeuner', 'le dîner', 'le souper'], 1, 3, 'dîner = midi (Suisse, Belgique, Québec).')] },
    { id: 'fr-precision', l: 'C2', cat: 'Style', ecat: 'collocation', title: 'Précision lexicale et collocations', sum: 'prendre une décision, poser une question, émettre une hypothèse, mettre en œuvre…',
      explain: ['Les collocations ne se traduisent pas : prendre une décision (pas "faire"), poser une question, émettre une hypothèse, formuler une demande, mettre en place / en œuvre, prendre en charge un patient.', 'Éviter les anglicismes et italianismes : "réaliser" = se rendre compte (sens anglais critiqué) → "effectuer un examen" ; "supporter" ≠ soutenir.', 'Verbes précis plutôt que faire/dire/mettre : effectuer, réaliser, souligner, préciser, instaurer.'],
      ex: ['Nous avons pris en charge le patient à 3 heures.', 'Permettez-moi de formuler une hypothèse.'],
      use: 'Réécris un texte en remplaçant les verbes vagues par des verbes précis.',
      x: [mc('___ une décision', ['faire', 'prendre', 'donner'], 1, 1, 'prendre une décision.'), mc('___ une hypothèse', ['émettre', 'faire sortir', 'donner'], 0, 2, 'émettre/formuler une hypothèse.'),
        gap('Le patient a été pris en ___ par le SAMU.', 'charge', 2, 'prendre en charge.', M), fix('Nous avons fait un examen approfondi et nous avons dit les résultats à la famille.', ['Nous avons effectué un examen approfondi et nous avons communiqué les résultats à la famille.'], 3, 'Verbes précis : effectuer, communiquer.', M)] },
    { id: 'fr-inversion', l: 'C2', cat: 'Style', ecat: 'grammar', title: 'Inversion stylistique', sum: 'Peut-être viendra-t-il. Aussi avons-nous décidé… Sans doute est-ce…',
      explain: ['Après peut-être, sans doute, aussi (= donc), ainsi, à peine, du moins en tête de phrase, l\'écrit soutenu inverse le sujet : Aussi avons-nous décidé de reporter l\'intervention.', 'Alternative courante : peut-être que + ordre normal : Peut-être qu\'il viendra.', 'Inversion après une citation : « Je reviens », dit-elle.'],
      ex: ['À peine était-il arrivé que l\'alarme a sonné.', 'Aussi avons-nous modifié le protocole.'],
      use: 'Réécris un paragraphe en registre soutenu avec deux inversions.',
      x: [tr('Peut-être qu\'il viendra. (soutenu)', 'Peut-être', ['Peut-être viendra-t-il.'], 2, 'Inversion après peut-être.'), mc('"Aussi avons-nous décidé…" — "aussi" signifie ici :', ['anche', 'perciò / quindi', 'tuttavia'], 1, 2, 'aussi + inversion = donc.'),
        fix('Aussi nous avons décidé de reporter. (soutenu)', ['Aussi avons-nous décidé de reporter.'], 3, 'aussi (= donc) + inversion.')] },
  ];

  LOS.lang.register({ code: 'fr', grammar });
})();
