#!/usr/bin/env node
/* Build for Vercel (and local testing). Zero dependencies besides @supabase/supabase-js.
 *  1. reads SUPABASE_URL / SUPABASE_ANON_KEY from the environment (or a local .env file)
 *  2. refuses to build if a secret / service-role key was supplied by mistake
 *  3. copies the static app into dist/, vendors the Supabase client, writes dist/js/env.js
 *  4. stamps the service worker with a version and the list of files to precache */
'use strict';
const fs = require('fs');
const path = require('path');
const ROOT = path.join(__dirname, '..');
const DIST = path.join(ROOT, 'dist');

function loadDotEnv() {
  const f = path.join(ROOT, '.env');
  if (!fs.existsSync(f)) return;
  fs.readFileSync(f, 'utf8').split(/\r?\n/).forEach((line) => {
    const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/);
    if (m && process.env[m[1]] === undefined) process.env[m[1]] = m[2].replace(/^['"]|['"]$/g, '');
  });
}
function fail(msg) { console.error('\n✖ BUILD STOPPED: ' + msg + '\n'); process.exit(1); }
function jwtRole(key) {
  try { return JSON.parse(Buffer.from(key.split('.')[1], 'base64url').toString('utf8')).role; } catch (e) { return null; }
}
function copyDir(src, dst, filter) {
  fs.mkdirSync(dst, { recursive: true });
  for (const e of fs.readdirSync(src, { withFileTypes: true })) {
    const s = path.join(src, e.name), d = path.join(dst, e.name);
    if (filter && !filter(s)) continue;
    if (e.isDirectory()) copyDir(s, d, filter); else fs.copyFileSync(s, d);
  }
}
function listFiles(dir, base = dir) {
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap((e) => {
    const p = path.join(dir, e.name);
    return e.isDirectory() ? listFiles(p, base) : [path.relative(base, p).split(path.sep).join('/')];
  });
}

loadDotEnv();
const url = (process.env.SUPABASE_URL || '').trim().replace(/\/$/, '');
const key = (process.env.SUPABASE_ANON_KEY || process.env.SUPABASE_PUBLISHABLE_KEY || '').trim();
const onVercel = !!process.env.VERCEL;

if (key.startsWith('sb_secret_') || jwtRole(key) === 'service_role') {
  fail('SUPABASE_ANON_KEY contains a SECRET / service_role key. Never expose it in a website.\n  Use the "anon" (legacy) or "publishable" key from Supabase → Project Settings → API Keys,\n  and rotate the secret key you pasted (it may have been exposed).');
}
if (!url || !key) {
  if (onVercel) fail('SUPABASE_URL and SUPABASE_ANON_KEY are not set.\n  Vercel → Project → Settings → Environment Variables → add both, then redeploy.');
  console.warn('⚠ SUPABASE_URL / SUPABASE_ANON_KEY not set: the app will show the "configuration missing" screen.');
}
if (url && !/^https:\/\//.test(url) && !/^http:\/\/(localhost|127\.0\.0\.1)/.test(url)) fail('SUPABASE_URL must start with https:// (e.g. https://abcd1234.supabase.co)');

const vendor = path.join(ROOT, 'node_modules', '@supabase', 'supabase-js', 'dist', 'umd', 'supabase.js');
if (!fs.existsSync(vendor)) fail('@supabase/supabase-js is not installed. Run: npm install');

fs.rmSync(DIST, { recursive: true, force: true });
fs.mkdirSync(DIST, { recursive: true });
for (const f of ['index.html', 'manifest.webmanifest', 'sw.js']) fs.copyFileSync(path.join(ROOT, f), path.join(DIST, f));
copyDir(path.join(ROOT, 'css'), path.join(DIST, 'css'));
copyDir(path.join(ROOT, 'js'), path.join(DIST, 'js'), (p) => !p.endsWith('env.js'));
copyDir(path.join(ROOT, 'assets'), path.join(DIST, 'assets'));
fs.mkdirSync(path.join(DIST, 'vendor'), { recursive: true });
fs.copyFileSync(vendor, path.join(DIST, 'vendor', 'supabase.js'));

const version = (process.env.VERCEL_GIT_COMMIT_SHA || '').slice(0, 8) || Date.now().toString(36);
fs.writeFileSync(path.join(DIST, 'js', 'env.js'),
  '/* Generated by scripts/build.js — public values only (protected by Row Level Security). */\n' +
  'window.LOS_ENV = Object.freeze(' + JSON.stringify({ SUPABASE_URL: url, SUPABASE_ANON_KEY: key, VERSION: version }) + ');\n');

const precache = ['./'].concat(listFiles(DIST).filter((f) => f !== 'sw.js').map((f) => './' + f));
const sw = fs.readFileSync(path.join(DIST, 'sw.js'), 'utf8').replace('__BUILD_VERSION__', version).replace('__PRECACHE_LIST__', JSON.stringify(precache, null, 0));
fs.writeFileSync(path.join(DIST, 'sw.js'), sw);

console.log(`✔ Built dist/ (version ${version}, ${precache.length} files)` + (url ? ` → ${url}` : ''));
